### ISSUE TITLE
a.jsperf.com newer than github

### ISSUE THREAD

**Issue by olore** [mathiasbynens/jsperf.com#101]
I'm having trouble running from the cloned source (JS errors) & realized that the assets on a.jsperf.com are newer than the source I cloned from github. Pointing my local to use a.jsperf.com as the asset URL, everything works as expected.

Can we get the latest running on jsperf.com committed into git?

**Comment by mathiasbynens** [comment]
We use `_tmp/build.php` for this. It fetches the latest version of Platform.js and Benchmark.js, concatenates these libraries together, and minifies the result.

Adding this to the GitHub repository for jsperf.com would introduce lots of commit noise (1 “update” commit every time Benchmark.js gets an update). Any suggestions?

**Comment by olore** [comment]
i wonder if we can do something with submodules, will take a look

**Comment by olore** [comment]
Thanks for the info. I am going to close this. 
I've forked & started using submodules & grunt to build the necessary files.
