### ISSUE TITLE
Strange results of a particular test in firefox

### ISSUE THREAD

**Issue by satazor** [mathiasbynens/jsperf.com#103]
The [test](http://jsperf.com/oop-benchmark/79) that has this strange behavior basically measures the performance of some OOP libraries.

The test consists in the instantiation of a Class (that has 2 levels of inheritance) and a call to setAddress() (which results in 2 super calls).

I'm the creator dejavu, which is the one that is having strange results in Firefox.
I got somewhat impressed with the results and made a profiling myself.
I took two screenshots, one of the profiling of dejavu (optimized) and what of my.Class.
The profiling results actually show that dejavu takes much less time in the construction of the instance and the setAddress() call:

dejavu profiling: http://cl.ly/image/3I142l362g2o
my.Class profiling: http://cl.ly/image/450J2l2S2z41

But on Firefox 17, dejavu is 45% slower than my.Class in jsperf.
The situation is even worse if we test on Firefox Aurora (19) which shows that dejavu is 78% slower.

**Comment by satazor** [comment]
By the way, the profiling was done with https://developer.mozilla.org/en-US/docs/Performance/Profiling_with_the_Built-in_Profiler

**Comment by satazor** [comment]
After further investigation, it seems that is not a jsperf issue.
Will reopen again if necessary.

**Comment by satazor** [comment]
@jdalton and @mathiasbynens I found the culprit. You are gonna like this: http://jsperf.com/strange-behavior-prototype-inherit

**Comment by jdalton** [comment]
Yap, I believe it. I've seen similar engine optimization misses while  deving Lo-Dash:
https://github.com/bestiejs/lodash/blob/v0.10.0/lodash.js#L2992-L2993 (this was for FF)

**Comment by satazor** [comment]
Can you guys please vote so it can be fixed faster?

https://bugzilla.mozilla.org/show_bug.cgi?id=816439
https://bugzilla.mozilla.org/show_bug.cgi?id=610296
