### ISSUE TITLE
AnotherJS breaks due fragile descriptors

### ISSUE THREAD

**Issue by WebReflection** [mathiasbynens/jsperf.com#104]
AnotherJS enriches `Object.prototype` and `Object.defineProperty` in a way that is able to break every library that uses weak ES5 descriptors.

[Test using AnotherJS](http://jsperf.com/issue-104)

The fix could be that descriptors are created via `Object.create(null)` so no inheritance is used. Unable to test this right now but the problem has been discussed in ES5 and agreed ES6 won't behave like that.

**Comment by mathiasbynens** [comment]
This sounds like something for Benchmark.js /cc @jdalton

**Comment by jdalton** [comment]
This has nothing to do with Benchmark.js, though Benchmark.js does have code to work with descriptors it doesn't use it by default.

**Comment by WebReflection** [comment]
and you closed this because ...

**Comment by jdalton** [comment]
> and you closed this because ...

Because your lib added a non-writable `invoke` property to the `Object.prototype` which causes the `Benchmark.invoke` assignment to throw in strict mode.

jsPerf doesn't restrict you and allows you to break a benchmark or test page.

**Comment by WebReflection** [comment]
you can always configure inherited properties through `Object.defineProperty(Benchmark, "invoke", Object.create(null, {invoke:{value:invokeCallback}}))` but I bet you won't do this and keep Benchmark weak, right? So, will you consider a patch for this?

**Comment by WebReflection** [comment]
[pull request here](https://github.com/mathiasbynens/jsperf.com/pull/105)
