### ISSUE TITLE
http://jsperf.com/ failed to load. When trying to create a new test.

### ISSUE THREAD

**Issue by chrsr** [mathiasbynens/jsperf.com#106]
When attempting to create a new test with jQuery in the "Preparation code HTML" the site fails.

Chrome (latest) responds with:
No data received
Unable to load the webpage because the server sent no data.
Here are some suggestions:
Reload this webpage later.
Error 324 (net::ERR_EMPTY_RESPONSE): The server closed the connection without sending any data.

Firefox (latest) also fails.

**Comment by mathiasbynens** [comment]
Can you provide a link to an example test case where this issue occurs?

**Comment by chrsr** [comment]
Hi Mathias,

I've discovered that the issue only occurs when I'm including jQuery or any of the libraries in my preparation code. I'm sure this would have been reported if everyone was getting the error, unfortunately I'm not getting any feedback as to why the response is failing.

I can access the jQuery CDN url directly: http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js

I've also uploaded a screen video of what I'm getting: http://www.youtube.com/watch?v=Lb_-h-e8STM

Potentially it's just me or my network :(

Cheers
Chris

**Comment by jdalton** [comment]
I'm going to close this as a one off issue.

**Comment by chrsr** [comment]
Fair enough :)
