### ISSUE TITLE
button to remove test case

### ISSUE THREAD

**Issue by Daniel-Hug** [mathiasbynens/jsperf.com#107]
There is a button to add additional code snippets for comparison, but no buttton to remove a code snippet from the comparison.

This is kinda essential I would think.

**Comment by mathiasbynens** [comment]
http://jsperf.com/faq#remove-snippet

**Comment by ricokahler** [comment]
@mathiasbynens 

> clear the ‘title’ and ‘code’ fields for the snippet you want to remove and save your changes.

that didn't work for me. when i try to do that, I get a validation error:

> Please enter a title for this code snippet.

There should be a button to remove a snippet :)
