### ISSUE TITLE
REC: is the graph sizing bad for performance decisions?

### ISSUE THREAD

**Issue by gcb** [mathiasbynens/jsperf.com#109]
testing the waters before i start sending patches.

I love the bar graph, but for performance considerations, i don't care much when looking at the graph if method X or Y is 300,000x or 250,000x as fast as another method in chrome. What i mostly care about is which one is faster in IE8, but thanks to the 300,000x bar, i can't see a big difference such as 40,000x or 70,000x in IE8, which would definitely make me choose the later.

I usually use the table view for that, but one graph that auto scales per-browser would make that much, much easier to visualize.

If i'm not alone here i will work on the code. (as for myself alone i use the site maybe once a quarter, so i can live with the table...)

**Comment by jdalton** [comment]
I agree it can be annoying but have also just used the table view when needing a clearer picture. I will mark this as wontfix unless @mathiasbynens wants further digging.
