### ISSUE TITLE
Remove or hide anomalies

### ISSUE THREAD

**Issue by Mottie** [mathiasbynens/jsperf.com#111]
If you look at [this graph](http://jsperf.com/read-innerhtml-vs-innertext-vs-nodevalue-vs-textcontent/6), you'll see a huge spike for Firefox 17.0... maybe it's real? I ran it again in Firefox 18.0 with similar but not as drastic results. Honestly, I think something in flawed in those tests - how is MooTools `get('text')` ~3x faster than `textContent`?

So, I guess I'm asking, is there a way to remove or hide results, or rescale the graph to look at more reasonable results.

**Comment by jdalton** [comment]
The graphs show what's reported, if the test is invalid or not. For anomalies, the more you run a test the more it will even out.
