### ISSUE TITLE
JSPerf breaks when evaluating toggle() variations

### ISSUE THREAD

**Issue by jhfrench** [mathiasbynens/jsperf.com#115]
While testing my answer to [Adding HTML5 hidden attribute support to jQuery .toggle() method](http://stackoverflow.com/questions/14635847/adding-html5-hidden-attribute-support-to-jquery-toggle-method), I created a [JSPerf test](http://jsperf.com/hidden-premium) to determine how much slower `.toggle(function() {...})` would be compared to `.toggle()`. To my amazement, the script with additional processing is reported to execute faster! Besides the results being counter-intuitive, I suspect a problem because I also see the toggling on the screen long after the results have returned.

How can I "fix" my test to get accurate results?

[This question](http://stackoverflow.com/questions/14636333/jsperf-breaks-when-evaluating-toggle-variations) is also on StackOverflow if you feel like answering there...

**Comment by jdalton** [comment]
After reviewing the source and the API docs, I believe you're using the API incorrectly (passing a `callback`).
I ran this test which also suggests incorrect API usage:

``` js
// works the same as your jsfiddle example
$('button').click(function() {
    $('#myElement').toggle(function() {})
})
```

http://code.jquery.com/jquery-1.9.0.js
http://api.jquery.com/toggle/

**Comment by jhfrench** [comment]
Using the jQuery .toggle() incorrectly? But it works in the fiddle, and even works in the JSPerf test (for the first 100+ iterations)...

**Comment by jhfrench** [comment]
Fiddle here: http://jsfiddle.net/jhfrench/g8Sqy/

**Comment by jdalton** [comment]
Ah yap, I replaced it with:

``` js
// works the same as your jsfiddle example
$('button').click(function() {
    $('#myElement').toggle(function() { alert("called") })
})
```

and I get the alert, at the end of the collapse.That means this is an async action an not suitable for the regular JSPerf test configuration, you could try the defer test option, but I think in this case it's not going to show you what you want.

**Comment by jhfrench** [comment]
Darn. Anyway, thanks for taking the time...and thanks for JSPerf!
