### ISSUE TITLE
FAQ: IE Browser Mode

### ISSUE THREAD

**Issue by jhfrench** [mathiasbynens/jsperf.com#116]
Question for your FAQ?
"If I'm using IE9 and I switch "Browser Mode" to IE7 (using Tools > "F12 developer tools") then run a JSPerf test, will I get results that are pretty much the same as running a "native" version of IE7?"

**Comment by jdalton** [comment]
Good question! The answer is **no**, IE  browser modes simply emulate the JS oddities and don't simulate actual perf of the older browser.
