### ISSUE TITLE
browser scope IDs vs slug

### ISSUE THREAD

**Issue by ainthek** [mathiasbynens/jsperf.com#118]
Could you PLEASE provide some sort of slug-name to browserscopeKey mapping ? 
We want to access results of our tests, using the slug name/edition,and finding the browserscope key by "clicking" is not very "machine friendly".

Please can you provide some sort of JSON output service describing individual tests ? is there any ? did we miss something ?

Also banning YQL in robots.txt did not help very much in our prevoius approach.

Thanx a lot

**Comment by jdalton** [comment]
I think this is out of scope for jsperf, we use the browserscope service and their scripts for integration.
