### ISSUE TITLE
Create browser extensions to run tests privately against external web pages

### ISSUE THREAD

**Issue by AtariDHD** [mathiasbynens/jsperf.com#119]
It would pretty terrific to have browser extensions that would allow me to use jsperf against my own web pages. For example, if I needed to profile a private web app with JS code that needs to run in the context of pages generated by the web app.  The browser plugin would provide privacy for proprietary code, enable benchmarking of scenarios not possible with jsperf.com, and could be a good avenue to commercialize jsperf.

Anyhow, thanks for a great tool!!

**Comment by jdalton** [comment]
You can use [Benchmark.js](http://benchmarkjs.com), this is what jsPerf uses under the hood.
