### ISSUE TITLE
Specify javascript library versions

### ISSUE THREAD

**Issue by tomByrer** [mathiasbynens/jsperf.com#120]
I assume that `<script src="//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js">` pulls the newest released jQuery lib.  I recommend a specific library version always be linked to (eg [1.9.1](//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js)) for 3 reasons:
##### Tests may be built with features that are dropped or changed

Libraries try to be backwards compatible, but there is no guarantee.  Things may be dropped or behaviors changed, rendering old tests incorrect.  Seems a few people had issues going from jQuery 1.8.3 to 1.9.0.
##### Libraries may roll out performance changes

Suppose that jQuery improved selector handling speed in version 1.9.4; that could twist many old tests.  I'm sure if cdnjs allowed 1.\* version downloading, that could throw off some old tests with lo-dash, since I know there is often new awesome.
##### Improved caching

Redirects inherently have [short cache times](https://groups.google.com/forum/#!msg/google-ajax-search-api/dWVzQF_YWCM/Y3-R738wh78J).

Please consider the following (high priority to low):
- Change your handy library buttons in the new posting page to paste only to the latest direct versions.
- Warn when users create & edit tests to use the latest direct versions (script to check?).
- Warn visitors that redirected versioning may throw results off.

Thanks for your consideration & your awesome tool!

**Comment by mathiasbynens** [comment]
> Change your handy library buttons in the new posting page to paste only to the latest direct versions.

I don’t want to have to update jsPerf every time jQuery, Prototype, MooTools, YUI, Dojo, Ext Core, or My Library gets an update. I don’t want to rely on a third-party API just to get the latest available version number for a given library.

Caching is not an argument here IMHO; jsPerf is a testing tool for developers and the actual load time of the page doesn’t really matter. (What matters is that the benchmarks are accurate.)

> Tests may be built with features that are dropped or changed
> Libraries may roll out performance changes

Those are good points, and I actually considered these things when I added those buttons, but see my point above. I don’t want to have to update jsPerf every time a new library version is released, but at the same time I want to make it easy for developers to quickly add a `<script>` element for jQuery.

It’s easy enough to turn `<script src="//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js">` into `<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js">` if that’s what you need.

**Comment by mathiasbynens** [comment]
> Warn when users create & edit tests to use the latest direct versions (script to check?).

I like this idea.

**Comment by tomByrer** [comment]
Thanks for the reply!

The caching is a very minor issue.

I guess since jsPerf is targeted at developers, I would hope they'd be wise enough to target a specific version.  Though a ".#" could be easy to miss.

> > Warn when users create & edit tests to use the latest direct versions (script to check?).
> 
> I like this idea.

Thanks.  Maybe a quick solution would be to add a comment to your buttons? eg
`<script src="//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js">`
`// Best practice: edit the URL number to a specific version, to ensure future versions don't break your test`

**Comment by jdalton** [comment]
Imma give this a :+1:.
I see devs linking to edge only cdn versions and raw master files on github  **all** **the** **time**.

We might also add a [rawgithub.com](http://rawgithub.com/) note to the FAQ (sep issue)

**Comment by tomByrer** [comment]
Thanks jd

(still brainstorming)  I am concerned about test creators pasting in their own version aliases though, & not just your buttons.  Perhaps just a short warning in the edit page, with a link to a more educational doc would be good?  Scanning the entered code & popping up warnings would be more foolproof, but alot of engineering on your end.

I do appreciate @mathiasbynens concern about the editor's button maintenance (& I agree; [YUI](http://yuilibrary.com/) is already at v3.9.1 vs your button's 2.9.0).  Could be a weekly task if you really wanted to update all buttons.  Would an outside database that you could grab the newest version number of of help to you guys?

**Comment by mathiasbynens** [comment]
[As mentioned before](https://github.com/mathiasbynens/jsperf.com/issues/120#issuecomment-15867789), I really dislike the idea of relying on a third-party API just to get the latest available version number for a given library.

**Comment by jdalton** [comment]
> Imma give this a +1.
> I see devs linking to edge only cdn versions and raw master files on github all the time.

Browsers are taking care of this as they start to respect GitHub's mimetypes.

**Comment by tomByrer** [comment]
Umm, did you accidentally close the wrong issue?

You can close if you want, but I don't understand the reason please?
This issue is versions that keep changing via 1xx redirects from //ajax.googleapis.com so that the tests after months/years are invalid.   **not** about raw.github.com at all (there is rawgithub like you mentioned before).

This report is still on my mind;  the only solutions I have so far is
- parsing .json from [jsDelvr](http://api.jsdelivr.com/packages.php) &/or [cdnjs](http://cdnjs.com/packages.json) (kinda uses API like Mathias doesn't like, but so do redirects from ajax.googleapis.com/ajax/libs/**_/1/**_)
- small in-page info/pop-down to instruct specific version linking & rawgithub.com
- a tutorial that teaches best practices.   [Experimented](https://github.com/tomByrer/jsperf-introjs) with injecting Intro.js via bookmarklet that sometimes works.
- New browserscope entry per new JS library version (like new entry per browser version)

**Comment by jdalton** [comment]
@tomByrer 
I was replying to

> Imma give this a +1.
> I see devs linking to edge only cdn versions and raw master files on github all the time.

To address your issue, I think jsPerf should try to stay away from mucking with dev's code as much as possible. It's trivial to fork a test and lock in a version of a lib if devs failed to do so on some revision.
