### ISSUE TITLE
No differentiation between Safari and UIWebView executed tests on iOS 

### ISSUE THREAD

**Issue by andydavies** [mathiasbynens/jsperf.com#121]
I ran this test http://jsperf.com/unzip-vs#chart=bar in both Safari and a UIWebView (Tweetbot)

Running it in UIWebView is slower due to the lack of JIT but there's seems to be no way to see this differentiation from the test results.

**Comment by jdalton** [comment]
This is something to [report to Browserscope](https://code.google.com/p/browserscope/issues/list).

**Comment by andydavies** [comment]
Raised as: https://code.google.com/p/browserscope/issues/detail?id=344

**Comment by jdalton** [comment]
@andydavies Thanks!
