### ISSUE TITLE
Add OS to Browserscope.

### ISSUE THREAD

**Issue by OJayRobinson** [mathiasbynens/jsperf.com#122]
It would be useful to include device / operating system information to Browserscope.  Currently Android Chrome and Desktop chrome both record results in the same place (Chrome 26).  But the results can be different enough that it is worth knowing.

**Comment by jdalton** [comment]
We use the scripts Browserscope provides.
If you'd like Browserscope to collect more info, you might [raise an issue on their bug tracker](https://code.google.com/p/browsersec/issues/list) to do so.
