### ISSUE TITLE
Run all tests once before starting to gather actual data.

### ISSUE THREAD

**Issue by Req** [mathiasbynens/jsperf.com#123]
This is a feature request. I sometimes run into tests where the first test or tests run fine, but one of the lower ones fail, making the results a little inconclusive. It would be great if there was for example an option/checkbox/button that when enabled or clicked, would run all tests once just to see that they actually work before starting to run the entire benchmark. This way I could simply go to another rev or create a new one before wasting time waiting for working results when one fails on my target browser (Yeah, IE).

**Comment by jdalton** [comment]
I've seen devs add this on their own as part of the setup.
