### ISSUE TITLE
Test not registered in Firefox Aurora

### ISSUE THREAD

**Issue by i-like-robots** [mathiasbynens/jsperf.com#124]
Tests appear to run just fine but results are not registered, I've not been able to find a reason yet so I'll just leave this hanging here...

User agent string `Mozilla/5.0 (Windows NT 6.1; WOW64; rv:22.0) Gecko/20130424 Firefox/22.0`

**Comment by mathiasbynens** [comment]
This is a Browserscope issue. Sorry, nothing we can do about that. Please ping the Browserscope folks!

**Comment by jdalton** [comment]
Here is their issue tracker [code.google.com/p/browserscope/issues/](https://code.google.com/p/browserscope/issues/list).

**Comment by i-like-robots** [comment]
Will do, cheers guys

**Comment by i-like-robots** [comment]
Browserscope appears to detect the browser correctly as Firefox 22, I don't have enough knowledge about their service to really work out and report the problem I'm afraid =(

**Comment by mathiasbynens** [comment]
Did you try clicking the various filters in the jsPerf UI? ![](http://i.imgur.com/QBhammi.png) Nightly/Canary/Beta/Aurora versions of browsers aren’t shown by default.

**Comment by i-like-robots** [comment]
Hmm, no luck there - this is the test I was running if it helps at all: http://jsperf.com/jquery-eq-method-vs-eq-pseudo-selector
