### ISSUE TITLE
Incomprehensible problem on jsPerf in IE9 with some variable name

### ISSUE THREAD

**Issue by termi** [mathiasbynens/jsperf.com#125]
http://jsperf.com/variable-name-ie-and-jsperf

In IE9 error occurs when I run this test. The problem in variable name 'e$0'. When I replace it to '$e0', for example, test works fine.

This problem is only in jsPerf. When I run this script in IE9 from file or in console, no error occurs

**Comment by jdalton** [comment]
This bug has been fixed in Benchmark.js edge, but has not been pushed to jsPerf.com

**Comment by jdalton** [comment]
Should be fixed now.
