### ISSUE TITLE
Unreliable async test mechanism

### ISSUE THREAD

**Issue by medikoo** [mathiasbynens/jsperf.com#128]
I approached that issue while trying to compare two very close API's, where one resolves callback in async manner (forces next tick resolution), and other doesn't do that. For fair comparison I decided to test them both marked as "async" (so both have deferred.resolve overhead).

Results were opposite from what I expected and from what real world gives. Numbers were in favor of API that forces next tick resolution which in real usage is many times slower.

I simplified the test case: http://jsperf.com/async-jsperf-test

Following

``` javascript
(function () { deferred.resolve(); }());
```

turns out to be over three times slower than:

``` javascript
setImmediate(function () { deferred.resolve(); });
```

![screen shot 2013-05-27 at 14 43 44](https://f.cloud.github.com/assets/122434/568065/1ee75f1a-c6cb-11e2-8ec3-0b65517d0d9a.png)

One of the reasons is that probably jsperf forces asynchronicity of a test, and just that adds unreliable overhead. I believe that to have correct results jsperf shouldn't force any own asynchronicity. If sync test was marked as async, it should run nearly as fast as if it was not marked as async.

I would expect that  _Sync (async)_ test is slightly slower than _Sync_ test (due to _deferred.resolve_ overhead), and both _Sync_ tests turns out faster than _setImmediate (async)_ test.

Other note, it would be nice to introduce less generic name for the async resolution (e.g. `jsPerf.resolve`. I wanted to test _deferred_ library and needed to change it's name to be able to make async test.

**Comment by jdalton** [comment]
Synchronous async will no longer be supported and has been removed in benchmark.js. This helps avoid issues with `setImmediate` tests.

**Comment by medikoo** [comment]
@jdalton you mean that jsperf will throw if `deferred.resolve` would be called in same event loop?

**Comment by jdalton** [comment]
Meaning it could hit the recursive call stack limit and throw an error yap. Deferred calls should not be executed synchronously.

**Comment by medikoo** [comment]
I mean, will running a test like _Sync (async)_ here http://jsperf.com/async-jsperf-test throw an exception?
This doesn't do any logic that could introduce infinite recursion.

How do you want to prevent synchronous resolution? What _"will no longer be supported"_ means?

**Comment by jdalton** [comment]
Yes, if `invoke` is synchronous then calling `resolve.defer()` will call the next test iteration or sample and do so until the call stack limit is hit or the max test time is hit.

**Comment by medikoo** [comment]
@jdalton ok, I think I got what you mean. Thanks.

**Comment by medikoo** [comment]
@jdalton Will that also mean that it won't be possible to get reliable results when comparing async tests with sync?

At least results of http://jsperf.com/async-jsperf-test-2 are not realistic. In that case `setImmediate` overhead is about 1-2% of total computation time, and jsperf shows that async test is 5 times slower.
