### ISSUE TITLE
long setup / teardown will crash the highlighter

### ISSUE THREAD

**Issue by ArkahnX** [mathiasbynens/jsperf.com#129]
I'm running jsPerf locally, and after manually breakpointing index.php, and then testPage.tpl, I discovered that the location the page was crashing (It was giving me a 101 (net::ERR_CONNECTION_RESET)) was at the highlight function around line 80. I'm gonna go take a look to see what the highlight function does, and maybe a way to make it work, but from what I can tell, it isn't throwing any errors (I have that set to explicitly show) and it isn't exceeding max execution time, it just...dies....

the code I'm working with is 7317 characters long, if that helps at all, and without the highlight function it works perfectly (The page renders).

Edit: highlighting appears to work if the indent function isn't called, leaving a length of 62853

**Comment by mathiasbynens** [comment]
Good catch. We’ve had issues with GeSHi’s excessive backtracing before — this is probably another one of those cases. Perhaps it can be fixed by updating to the latest GeSHi version?

**Comment by ArkahnX** [comment]
testing GeSHi 1.0.8.11, appears to not make any difference.

**Comment by ArkahnX** [comment]
maybe a temporary fix could be to not syntax highlight over a certain number of characters?

Not sure if that would be an adequate fix though, since I'm not sure if it's the length or the format that buggers things up.

**Comment by mathiasbynens** [comment]
Sounds good. That would avoid the issue in most cases. (It’s not strictly related to character count, but rather to the amount of backtracing GeSHi does, which in turn depends on the code that has to be highlighted.)

So, let’s add something like:

``` php
if (strlen($str) >= 50000) { // magic number :(
  return $str;
}
```

…at the top of the `highlight()` function: https://github.com/mathiasbynens/jsperf.com/blob/18328dd7bbc22684d3d7f26a888c1a8ef275b430/_inc/start.php#L252-L259

**Comment by mathiasbynens** [comment]
@ArkahnX Would you mind reporting this as a GeSHi bug? Please include the code you were trying to highlight.

**Comment by ArkahnX** [comment]
Would love to @mathiasbynens, however it appears that functionality of sourceforge is down at the moment. They tweeted about it 10 hours ago apparently. The page loads fine when I'm not logged in mind you, but...you can't really add a bug.

Also the temporary fix is no good. It doesn't appear to be a matter of length, and more of a matter of content. I'll see if I can play with my code some more to find out what is causing the system greif.

to keep things updated here, this is what my code sample looks like as the smallest I can get it while it still crashes. From here, remove any line, and it will work.

``` javascript
numberList.prototype = {
  maxValue: {
    u8: 255,
    i8: 127,
u:0,
    u16: 65536,
    i16: 32767,
    u32: 4294967295,
    i32: 2147483647,
    i64: 9223372036854775807
  },
array:[],
  minValue: {
    u8: 0,
    i8: -128,
    i16: -32768,
    u32: 0,
    i32: -2147483648,
    i64: -9223372036854775808
  },
  namesList: [],
  valuesList: [],
  maxSize: 0
};
```

I can't say that I see anything unusual about any of this code, except maybe GeSHi chokes on the numbers a little. Except... we are dealing with strings, so that doesn't make sense either. On my end, it's just a lack of understanding, so I'll do my duty and fire an appropriate bug over to GeSHi...when that starts working.

**Comment by jdalton** [comment]
Closing as a GeSHi bug?
