### ISSUE TITLE
define.amd breaks jsperf

### ISSUE THREAD

**Issue by kriszyp** [mathiasbynens/jsperf.com#13]
If jsperf.com is used with a AMD module loader (RequireJS, Dojo 1.7, bdLoad, Curl, or any other, that are an increasing number out there), then there is a `define.amd` global and when `define.amd==true` Benchmark.js will register itself as a module instead of as a global. The quick fix is to make sure `define.amd` is falsy before running Benchmark.js. There may be a more robust solution.

**Comment by mathiasbynens** [comment]
The easiest fix is moving Benchmark.js back to the `<head>` so that it appears before any of the preparation code has run — but I’d rather not do this as it would negatively affect performance of all test pages on jsPerf.

**Comment by jdalton** [comment]
I will kick around solutions in the morning, thanks!

**Comment by mathiasbynens** [comment]
Thanks to @jdalton, we just rolled out a tweak to our jsPerf deploy script that adds a workaround for this issue.

@kriszyp Any particular jsPerf test case we can try it on to see if it worked?

**Comment by kriszyp** [comment]
Beautiful, thank you! Here is a test that confirms your successful fix:
http://jsperf.com/jquery-vs-dojo-vs-mootools-dom/22
