### ISSUE TITLE
Allow embedding result graphs as images for GitHub wikis

### ISSUE THREAD

**Issue by CamiloMM** [mathiasbynens/jsperf.com#130]
I'd love to embed the graph from jsperf into a github wiki, this would only need an image link.

Is such a thing even possible? It seems they're rendered on the browser, but it would be very nice to have them as a server-generated image.

**Comment by mathiasbynens** [comment]
I suppose it would be possible to hook Browserscope’s JSON data up to the (deprecated) [Google Image Charts API](https://developers.google.com/chart/image/). I’m not sure if this is something that jsperf.com should take care of, though — it may be better suited as a user script or a browser addon.

**Comment by CamiloMM** [comment]
Google image charts API is deprecated? :(

But yes, that's a pretty good solution. The only problem is that it would be static, right? Unless from server-side this image was fetched and delivered dynamically using a single URL (like /slug/graph.png or something).

**Comment by jdalton** [comment]
At I don't plan to tackle this. Screen grabs work when needed.
