### ISSUE TITLE
Suggestion: Use something like Sauce Labs to allow users to run tests on multiple browsers quickly and easily

### ISSUE THREAD

**Issue by WillsB3** [mathiasbynens/jsperf.com#131]
Hi,

JSPerf is a great tool, so firstly, thanks! One of the largest problems I face when using it however is gathering test data. It would be fantastic if I could write a test case and then pick the browsers I want to run the test against from a list and then have JSPerf use something like Sauce Labs or BrowserStack to remotely run the tests on the chosen browsers. 

Sauce Labs have an "Open Sauce" plan which should allow the project to use the service for free. I imagine cost is obviously an important point here, as anything that costs is probably not viable, so this offering from SauceLabs would be worth looking into.

I appreciate this is potentially a massive development / re-architecting effort but just thought I'd throw this idea out there.

Would love to start a discussion around this.

**Comment by jdalton** [comment]
I don't want to rely on automation here (it's brittle).
