### ISSUE TITLE
Suggestion: tree view instead of list of revisions.

### ISSUE THREAD

**Issue by michal-kowalczyk** [mathiasbynens/jsperf.com#132]
Hey,
jsperf.com is great tool for JS optimization and I am really glad that you have created it. (-:

I think, it could be greater, if each next "extension" of test could be found in hierarchical structure, each user could propose better test for some specific usage. For instance:
root: http://jsperf.com/jquery-vs-createelement
root -> 0: http://jsperf.com/jquery-vs-createelement/2
root -> 1: http://jsperf.com/jquery-vs-createelement/3
root -> 2: http://jsperf.com/jquery-vs-createelement/4
root -> 3: http://jsperf.com/jquery-vs-createelement/5
root -> 4: http://jsperf.com/jquery-vs-createelement/6
root -> 4 -> 0: http://jsperf.com/jquery-vs-createelement/7

In this way it could be easier to find similar approaches to the same problem. Also, sometimes happens that the test could be great, but it has some small error that makes it invalid. Subnode (or branch) of it could resolve it.

**Comment by jdalton** [comment]
Each revision could be a complete rewrite of the last so there is nothing really binding one to the other.
