### ISSUE TITLE
Unexplained benchmark anomaly

### ISSUE THREAD

**Issue by datibbaw** [mathiasbynens/jsperf.com#133]
I've created a test here: http://jsperf.com/html-escaper-v2

It measures the performance between different implementations of HTML escapers; I've created one definition in the global scope, i.e. inside a `<script>` tag and another one inside `Benchmark.prototype.setup()`.

Somehow, the latter version performs twice as fast; how is that possible?

**Comment by jdalton** [comment]
That's a good question. The one in the setup is defined locally but I wouldn't think that would matter in this case because it's being assigned to the `String.prototype`.

**Comment by datibbaw** [comment]
It was suggested that perhaps the excessive use of regular expressions is throwing off the code generation that's used to construct the test suite. Perhaps that's an area you could look at?

**Comment by jdalton** [comment]
This issue seems to be resolved now. I also made a fork to confirm that both returned the same results.
