### ISSUE TITLE
Setting running variables in the URL ?

### ISSUE THREAD

**Issue by runsun** [mathiasbynens/jsperf.com#138]
The FAQ mentions that a #run can be attached to the URL to make it run without clicking the button. 

Is there anyway to add something to "preparation code" through the URL to make it run with different settings each time ?

For example, something like :

http://jsperf.com/document-getelementbyid#run#{size:10}
http://jsperf.com/document-getelementbyid#run#{size:100}
http://jsperf.com/document-getelementbyid#run#{size:1000}

**Comment by mathiasbynens** [comment]
You could do something like that yourself. E.g. http://jsperf.com/hasownproperty-vs-for-in#c200.

**Comment by runsun** [comment]
Thanks. That's really great. 

Based on this, is there any way to put the auto run hash (#run) and the variables in the example (#c200) in one url ?

For example,

http://jsperf.com/hasownproperty-vs-for-in#c200#run

or 

http://jsperf.com/hasownproperty-vs-for-in#run#c200

It seems that # only takes one var.

**Comment by mathiasbynens** [comment]
You could do that yourself. E.g. put `#300,600` in the URL and then use `location.hash.split(',')` to get each part, or something.

**Comment by runsun** [comment]
Your reply didn't answer my question, but I got it done. That is, it can auto-run (without #run) with varying parameter values. See:

http://jsperf.com/hasownproperty-vs-for-in/20

**Comment by jdalton** [comment]
Also the `ui.params` object will have a break down of params passed via the hash.

**Comment by runsun** [comment]
thx for sharing.

**Comment by runsun** [comment]
Updated:

Just found that we can do this:

.....url..... #size=100&min=10&max=200&run=true

and it will give:

ui.params =  {size: "100", min: "10", max: "200", run: "true"}

Since it has "run" set to true, it runs the tests automatically. Pretty cool.
