### ISSUE TITLE
Allow sorting the test table as soon as results are known

### ISSUE THREAD

**Issue by mathiasbynens** [mathiasbynens/jsperf.com#14]
Suggested by @pornel: http://twitter.com/pornelski/status/101578813804253184

**Comment by mathiasbynens** [comment]
This is probably not as needed anymore since jsPerf got charts. Still keeping this issue open though.

**Comment by jdalton** [comment]
Sorting is supported when u click on the column titles.
Not sure why sorting the non-browserscope results would be beneficial.

**Comment by mathiasbynens** [comment]
@pornel’s rationale is that currently it’s hard to find the second-to-best option after running the test. I agree, but I don’t really see why you’d want to.

**Comment by jdalton** [comment]
Ok table sorting couldn't hurt. We could make it happen when clicking on the results column... but first highlight the selected chart/filter :PPPP

**Comment by kornelski** [comment]
> I don’t really see why you’d want to.

When the first option is fast, but crazy/ugly/non-portable? And it's especially interesting in cases like "JavaScript template language shootoff" where you basically want a ranking.

**Comment by jdalton** [comment]
I will expose chart data on `ui.browserscope` to allow devs to access and manipulate the info.

**Comment by mhavard999** [comment]
3 years late to the conversation, but this table is not sortable by column:
![image](https://cloud.githubusercontent.com/assets/1484098/7516839/b4f13626-f49f-11e4-8f92-46fe63a5204c.png)
Clicking on "Test" or "Ops/sec" does nothing.  @jdalton claims they do sort (see above: https://github.com/mathiasbynens/jsperf.com/issues/14#issuecomment-2307508).  Did something change between now and 2011?

**Comment by mathiasbynens** [comment]
They never sorted.

**Comment by mhavard999** [comment]
So should this be re-opened?

**Comment by jdalton** [comment]
Naw, I don't see this getting added.
