### ISSUE TITLE
different results on test runner and browser scope

### ISSUE THREAD

**Issue by ahorn42** [mathiasbynens/jsperf.com#141]
sometimes I get different results desplayed on the test runner and browser scope. Which are the "right" ones? And is this an intendet behavior?
![jsperf](https://f.cloud.github.com/assets/5106205/868026/703f552a-f768-11e2-8099-6bef9cdb7fdb.PNG)

**Comment by mathiasbynens** [comment]
http://jsperf.com/faq#browserscope

**Comment by ahorn42** [comment]
Thanks for the fast answer :)
well, the faq says you "submit the results minus the margin or error (the lower limit of the confidence interval, i.e. the lowest suspected value) to Browserscope".

If I do this i.e. for "div without floor" I get 865,902,890 \* 0.0005 = 432,951.445 and  865,902,890 minus 432,951.445 is not 818,248,420. Didn't I understand your calculation or might something be wrong?
I am also confused about the fact, that every test has the exactly same value on browser scope?!

**Comment by jdalton** [comment]
There is a patch in Benchmark.js' `compare` method which may address this issue.
Here is the code to create the browserscope results: [plugin/ui.browserscope](https://github.com/bestiejs/benchmark.js/blob/57f683650aa6bf9cffbe9028787643f98fe74a39/plugin/ui.browserscope.js#L331-L385)
