### ISSUE TITLE
Test with 12 snippets runs only in Chrome

### ISSUE THREAD

**Issue by ahorn42** [mathiasbynens/jsperf.com#142]
This test with 12 snippets http://jsperf.com/for-variants runs only in Chrome, not in Firefox, not in IE, not in Opera (every Browser in the latest stabel version).

**Comment by mathiasbynens** [comment]
We were just updating to the latest version of Benchmark.js on the server. Please try again now that the new version is deployed.

**Comment by ahorn42** [comment]
Yes now it works ;-) - thanks!
