### ISSUE TITLE
IE7/8 javascript error

### ISSUE THREAD

**Issue by christianbodart** [mathiasbynens/jsperf.com#143]
hmmm this test http://jsperf.com/closure-vs-clean errors out in IE7/8 but doesn't seem to throw an error locally when using the same code (without jsPerf) may be the poor choice of variable names but it seems strange as the code isn't doing anything complicated

**Comment by christianbodart** [comment]
My bad : http://stackoverflow.com/questions/8548840/javascript-named-function-expressions-in-internet-explorer

**Comment by christianbodart** [comment]
After editing the named functions I'm still get errors in IE8 but before the tests are even run - 

http://jsperf.com/closure-vs-clean/5 line 1:13165

**Comment by christianbodart** [comment]
Sorry, I meant to say, this is occuring on all jsperf benchmarking pages

**Comment by jdalton** [comment]
@mathiasbynens We need to ensure the Lo-Dash version on jsPerf is the dist/lodash.compat.js version, as the default one is the modern build.

**Comment by mathiasbynens** [comment]
Done. @standardjs could you try again, please?

**Comment by christianbodart** [comment]
Great works thanks
