### ISSUE TITLE
creating test with only 1 test-case

### ISSUE THREAD

**Issue by getify** [mathiasbynens/jsperf.com#145]
I regularly find myself wanting to create a test with only one test-case, because my goal is to do cross-browser benchmarking of some piece of code, not just putting to two pieces of code head-to-head.

When I create a new test, it forces me to put something into the second test case, but then I can immediately edit and remove that, leaving the test with only one test case. I do this often, but it's a little annoying to have to go indirectly through it.

Could we:
1. Remove the validation that requires stuff in the second test case, allowing it to just be left blank and thus implicitly deleted?
2. Put a "X" delete button next to test cases, including the default second test case when creating a new jsperf. The simple rule then would be that you could delete any test case, but a test can never get to zero test-cases.

**Comment by jdalton** [comment]
Closing as stale. We'll still keep an eye on the popularity of the request.
