### ISSUE TITLE
Tweak CSS now that we’re back to using `<iframe>`s for embedding the Browserscope charts

### ISSUE THREAD

**Issue by mathiasbynens** [mathiasbynens/jsperf.com#146]
And remove these lines: https://github.com/bestiejs/benchmark.js/blob/1f2760c49028d5aa0a41895e6846792a9d2d8626/plugin/ui.browserscope.js#L1056-L1058

**Comment by jdalton** [comment]
I'll try to transition this to a dynamically created iframe to avoid the double page hit of `/embed`.

**Comment by jdalton** [comment]
fixed.
