### ISSUE TITLE
Update with changed from the .com

### ISSUE THREAD

**Issue by jdalton** [mathiasbynens/jsperf.com#147]
Several changes have gone into the .com but are not reflected here.
We should sync it before it's a major pain to sync.

**Comment by mathiasbynens** [comment]
Like what changes? The online version and the repo seem to be in sync and I don’t remember making any changes to the live site’s CSS without committing them…

**Comment by jdalton** [comment]
Isn't the build script different now to pull down lodash and replace portion of the code to avoid exporting incorrectly?

**Comment by jdalton** [comment]
Ah ya beat me to the commit :P

**Comment by mathiasbynens** [comment]
Ah sorry, I somehow misread your issue title as something CSS-related. You’re totally right!

Committed 3395d4c79b9eb27e7029298fb1f879a8b3d9729b and some others. Thanks!
