### ISSUE TITLE
Feature Request: Chart to Show Test Average Across All Browsers

### ISSUE THREAD

**Issue by kaleb** [mathiasbynens/jsperf.com#152]
It would be great to have a chart type that will show the average across all browsers instead of each browser broken out separately. That way a user can see which test demonstrates the most optimal method of performing a certain task across all browsers.

Bonus:

It would be great if you could kick out some outlying browsers or browsers you may not want to support, e.g. IE7

**Comment by runsun** [comment]
Before that feature is implanted, the data is actually available. I picked up a jsperf randomly:

http://jsperf.com/treewalker-on-document-fragment/6

and found it's data here:

http://www.browserscope.org/user/tests/table/agt1YS1wcm9maWxlcnIRCxIEVGVzdBiAgICEj8iDCAw

**Comment by jdalton** [comment]
Closing as stale. I don't see us tackling this anytime soon.
