### ISSUE TITLE
Setup and Teardown does not run for all tests.

### ISSUE THREAD

**Issue by Griffork** [mathiasbynens/jsperf.com#153]
Set up and tear-down snippets seem to run arbitrarily at different intervals, rather than once before and after each test is run.
See http://jsperf.com/setup-teardown for an example (you will need the console open).

Tested on Chrome 29.0.1547.76

**Comment by jdalton** [comment]
Dup of #150

**Comment by Griffork** [comment]
Then please can you update the FAQ's response on the issue because the question specifically states "before and after **each** clocked test loop".

> Is it possible to execute code before and after each clocked test loop, outside of the timed code region?
> That’s what Benchmark#setup and Benchmark#teardown are for. You can use the Setup and Teardown fields to use the same function(s) for all tests. To target specific tests, you can use ui.benchmarks[0].setup = function(){ … }; (and/or teardown) in the Preparation Code field, where 0 is the zero-indexed test ID.

**Comment by mathiasbynens** [comment]
@Griffork: “Before and after each clocked test loop” is absolutely correct. You were expecting setup/teardown to be run _inside_ the loop (i.e. not before/after each loop), once for every time the snippet gets executed.

**Comment by EamonNerbonne** [comment]
The FAQ isn't very obvious; I see lots of very misleading jsperf tests that seem to assume the flow is `loop{ <setup> <test> <teardown> }`

Frankly, I think that even if excluding setup timing is hard and reduces accuracy, it's still worth it: right now it's not possible to compare tests that require per-test setup with jsperf.

**Comment by jdalton** [comment]
> Frankly, I think that even if excluding setup timing is hard and reduces accuracy, it's still worth it: right now it's not possible to compare tests that require per-test setup with jsperf.

No way to do it.

**Comment by EamonNerbonne** [comment]
You could measure the time for each loop iteration test body, not the time for the the loop as a whole.  This will likely be wildly inaccurate, but the mean should nevertheless converge and you're doing ton's of loops anyhow.  Or, when the test is really slow and you're doing few loops the timing error is fairly low.

There are some related benefits there; you no longer would need to "auto-scale" the amount of iterations since you could conceptually to `while(duration-under-5sec)...`.

**Comment by Griffork** [comment]
I think the main problem is that on most platforms/browsers your smallest time increment is 1ms (not ns) and you're not getting accurate results at ~10 ms, or really at ~100 ms, because often a couple of million instructions can run in the space of about 1 ms, so the results would be very strange:

For example, Test A takes 8 ms, Test B takes 8.01 ms: large scale (if you're doing a heck of a lot of it) that 0.01 will probably matter (e.g. database writes for a bank) but unless you run ~100 tests, the difference in time will (on a favorable run) be just noticeable, but not accurate.

Now take a typical 10 line test for a, b and c, and a takes 0.0001 ms to execute, b takes 0.000099 to execute, and c takes 0.000098 to execute, and the only really difference shows when you run it ~100000 times. Most jsperfs that I have written have needed to have their loop run for ~30,000-100,000 times for the difference to be noticeable.

Therefore, since the smallest time increment is 1ms, and if you're only timing the loop in between each set-up and tear-down, the loop's duration for a lot of tests will report as being 0ms. And 0ms + 0ms is 0ms, so the results would be meaningless.

Let me know if anything I've said here is not clear.

**Comment by EamonNerbonne** [comment]
That's all true, but it's not actually a problem.

Let's say you're running a loop with 10000 iterations in 1 second, and the timer quantization is 1ms (call that a "tick").  That means your tests which actually take 0.1ms will usually report the incorrect time of 0ms, and for an _individual_ test this a problem.

But that's not a complete picture of what's happening.  We're reporting averages, not individual tests; and those ticks need to fall _somewhere_; so those 1000 timer ticks will be distributed somehow over the execution of your loop. The average will still be ok. It's just like a sampling profiler.

For example, if you start/stop the timer in each iteration such that a segment is excluded, there's another probability distribution which dictates how many ticks fall inside the tested region and how many outside.  Say the distribution is 90% setup, and only 10% tested region, then that means each test iteration has a 90% change of having 0 ticks; and a 9% chance of having a tick in the setup and a 1% chance of a tick in the test.  This is a pretty terrible distribution and , but even so, the mean is still 100+/- 10 ticks i.e. 100ms. (approx binomial, so  http://www.wolframalpha.com/input/?i=binomial+distribution+n%3D10000%2C+p%3D0.01 )

So even though many iterations will report 0ms, the average is still meaningful as long as the cumulative time is many multiples of a timer tick.

**Comment by EamonNerbonne** [comment]
The graph of the normal approximation is a little clearer: http://www.wolframalpha.com/input/?i=N%2810000*0.01%2C+10000*0.01*%281-0.01%29%29

**Comment by Griffork** [comment]
But what if the test can only run for between 0.01 and 0.05? Then you'll get a 100% chance of 0ms.
In my opinion if you were going to do something like that you'd first measure the setup and teardown times and then subtract them from the total result.

Even then it arguably won't be an accurate result because of optimisations the browser does on your code AND it's not too hard to set that particular way of doing things up with the current way things work.

**Comment by Griffork** [comment]
One more thing; how do you know that the setup is taking 90% of the time when both the setup and the test take less than 1ms to execute?

**Comment by EamonNerbonne** [comment]
@Griffork ; that's not how it works - jsperf scales the number of runs to fill a certain set amount of time i.e. some set amount of "ticks".  Even if a loop iteration takes only a tiny fraction of a tick, those ticks need to fall _somewhere_ and you'll still probabilistically get the right measurement.

Only if the overall duration of all iterations of the timed region together are near or below 1 tick would you expect to commonly measure 0 ticks.  But really, if that's the case... your code really is so much faster than setup/teardown that measurement is hard; it perfectly OK to report that.

**Comment by EamonNerbonne** [comment]
The reason why I think something like this is a good idea is because I've seen lots of DOM-interacting jsperfs that do some modification in the setup and some more modification in the test.  There's no hint right now that this means that the 1st iteration then runs in quite a different situation than the 2nd iteration and so on; it _looks_ like you're getting meaningful results, but really you're not.

For example: http://jsperf.com/empty-content-innerhtml-vs-dom
or: http://jsperf.com/fragment-vs-appendchild-vs-innerhtml  (subtle and nasty)

**Comment by Griffork** [comment]
Right, I come from a different kettle of fish: 
Most of what I've done so far is measuring binary array performance vs object access performance vs javascript array performance for different actions, or measuring string operations vs regular expressions or undefined checks vs null checks, and then the tests are extremely small; but if you're doing tens of thousands of these operations per frame, it's very important that you get it right.

Now the arrays/objects are created/reset/populated in the setup or teardown, and is usually an extremely time-intensive operation, which is why I think for this (set of) case(s) your solution would be far from optimal.

**Comment by EamonNerbonne** [comment]
Yeah, you want a per-test-set setup, but that's easily done in the page construction.

But you also want a per-test setup, if only to ensure a clean slate (a per-test teardown would probably be sufficient too, though less ideal since you might need to duplicate the cleanup between that teardown and the page setup).

The point is really that the current setup - per loop - has no purpose at all, regardless of the kind of code you're running.  You can essentially always stick whatever's in there into the page setup.
