### ISSUE TITLE
"Private" jsperfs?

### ISSUE THREAD

**Issue by fatso83** [mathiasbynens/jsperf.com#156]
Is private jsperfs in the making? I'd like to share a jsperf with some people at work, but it contains some copyrighted, proprietary library we make. So I can't make it searchable, but I would like it to be shareable ("secret" url á la Google Docs sharing).

**Comment by mathiasbynens** [comment]
This is already supported. Just don’t check the “publish” checkbox.

**Comment by tomByrer** [comment]
Non-published tests seem to still be available; they just are not listed via [Latest](http://jsperf.com/browse) or Revisions.  EG this is not directly listed: http://jsperf.com/native-vs-array-js-vs-underscore/7
Or how about this non-published test? http://jsperf.com/new-fake-temp-test
(I find having the non-published tests posted useful when I want to test in different browsers before 'publishing'.)

Likely the only way to make a 99.9% secure test is to [instal it yourself](https://github.com/mathiasbynens/jsperf.com#how-to-run-a-local-copy-of-jsperf-for-testingdebugging)

**Comment by krawaller** [comment]
Even if I don't check the "published" checkbox, my tests still show up in the search – that is not what I expected. Is it intended?!

See for example http://jsperf.com/search?q=jaco

**Comment by jdalton** [comment]
> See for example http://jsperf.com/search?q=jaco

I don't see anything. You could be seeing things because your session as jaco was still active.

**Comment by mathiasbynens** [comment]
Fixed
