### ISSUE TITLE
Run test cases in random order

### ISSUE THREAD

**Issue by dleppik** [mathiasbynens/jsperf.com#159]
Just-In-Time compilers can have extremely different performance characteristics, depending on other code that has already been compiled and optimized.  In some cases, one test may inadvertently optimize or pessimize another test. For this reason, the tests should be run in random order.

**Comment by jdalton** [comment]
We won't be introducing random run order. We do allow you to manually choose the order by clicking on the test title. We generate a new test per sample with random characters to the var names.
Your concern can possibly be handled by putting code in your `setup`.

Do you have a real world test case to point to?

**Comment by collinanderson** [comment]
it would help me with my test: http://jsperf.com/jquery-load-time
