### ISSUE TITLE
Craaaaash.

### ISSUE THREAD

**Issue by 19h** [mathiasbynens/jsperf.com#160]
I tweeted that at you 25 days ago, but here's a real issue for it: I had an issue with @juliangruber about intersections and created a test with some real numbers inside for its reproducibility. The test was created successfully .. but crashes the website when opened.

http://jsperf.com/intersections

Will give you a 500 after a minute or so.

:v:

**Comment by mathiasbynens** [comment]
I’m guessing this was a very large test (i.e. lots of data entered)?

**Comment by 19h** [comment]
Not quite sure about the size anymore.. but I assume it was

**Edit:** Yes, it was.
