### ISSUE TITLE
Removal bug, option to remove test-case

### ISSUE THREAD

**Issue by laukstein** [mathiasbynens/jsperf.com#161]
Following http://jsperf.com/faq#remove-snippet steps, it would not remove the test case but add a new one (following removal steps for http://jsperf.com/whatever/edit would add http://jsperf.com/whatever/2 and not remove anything).

What in case when we have http://jsperf.com/whatever/, http://jsperf.com/whatever/3, http://jsperf.com/whatever/4 and I wont to remove http://jsperf.com/whatever/2?

**Comment by mathiasbynens** [comment]
http://jsperf.com/faq#remove-snippet is about removing snippets from a test case. It’s not possible to remove an entire test case.

**Comment by laukstein** [comment]
What about to implement option to remove the entire test case?

**Comment by mathiasbynens** [comment]
Not gonna happen. jsPerf test cases are supposed to be public and permanent.

**Comment by laukstein** [comment]
And what about updating old old snippets that for example has outdated Ajax requests?
Currently http://jsperf.com/faq#remove-snippet will not update under the same URL, but will generate a new URL for it.
