### ISSUE TITLE
Browserscope Over Quota

### ISSUE THREAD

**Issue by tomByrer** [mathiasbynens/jsperf.com#162]
> This application is temporarily over its serving quota. Please try again later.

This has happened a few times the past few days.
Not sure of a good fix-action, maybe buffering results?  Or be able to turn off automatic result reads? (I often will test the same case on several browsers, & don't care about seeing results until the 4th-6th run-through.  Or I flip though several different revisions of the same case to see differences.)

I sent an email to @stevesouders as well.

**Comment by jdalton** [comment]
I pinged @elsigh about it a few days ago. It's on his todo.

**Comment by jdalton** [comment]
I'm closing this as it's not really our bug.

**Comment by tomByrer** [comment]
I agree the issue is on his end...
Do you think that jsPerf could buffer results, so when Browserscope goes down, at least the results are available?

**Comment by jdalton** [comment]
I don't think that'll happen, the whole point to using a third party like Browserscope, is to shift the burden & load to them.

**Comment by tomByrer** [comment]
> shift the burden & load to them

How true, thanks for the feedback!
I'll have to mentally note to record results somewhere when it is high-priority.

**Comment by jdalton** [comment]
> I'll have to mentally note to record results somewhere when it is high-priority.

No worries, I think this issue is only temporary.

**Comment by tomByrer** [comment]
I hope so, I'm trying to help [optimize a program](https://github.com/giakki/uncss/issues/16) by proving a utility script is faster than another.... maybe you heard of it, it is called low-dash or something?
;)

**Comment by elsigh** [comment]
Right on. I should have a fix in place soon
