### ISSUE TITLE
Insert new tests in-between existing rather than just append new tests to the end

### ISSUE THREAD

**Issue by heavensrevenge** [mathiasbynens/jsperf.com#163]
It would be really nice to be able to insert new tests in-between existing tests instead of being forced to add a new blank test to the end; copy & paste them all down to rearrange them far enough to insert a new test at a current/contextual position.

An enhancement/addition to this would be the ability to rearrange tests with a "handle" so the tests don't need to be copy & pasted around in order to be rearranged manually as of this moment.

**Comment by heavensrevenge** [comment]
Any opinion on this? Was I clear enough on the intent/description?

**Comment by mathiasbynens** [comment]
> Was I clear enough on the intent/description?

Yes.

But this is not a priority.
