### ISSUE TITLE
Update ua-parser link for submitting wrong browser identification

### ISSUE THREAD

**Issue by mbest** [mathiasbynens/jsperf.com#164]
At the bottom of the charts is the text "Browserscope thinks you are using ....  No?". The "No?" link goes to http://code.google.com/p/ua-parser/, but the repository is now at  https://github.com/tobie/ua-parser/

**Comment by mathiasbynens** [comment]
I believe this is a Browserscope bug. cc @elsigh

**Comment by elsigh** [comment]
Tru dat. But Browserscope may be out of sync with UA parser too. I think I might just need to remove that link No? link entirely..

**Comment by mbest** [comment]
Interestingly, if go to http://www.browserscope.org/ in IE11, it shows "Other", but at http://www.browserscope.org/ua, I get "IE 11.0".

**Comment by mbest** [comment]
If I change to Document mode 10, it shows up as "IE 11 in Compatibility Mode 10.0".

**Comment by elsigh** [comment]
Compatibility mode = nightmare. It's very likely Browserscope is just
behind ua-parser's updates for IE on this one.
