### ISSUE TITLE
Destructive Serverside Validation

### ISSUE THREAD

**Issue by npbenjohnson** [mathiasbynens/jsperf.com#173]
#172 Fix to allow deletion of test one on edit page makes it so that deleting test case 1 no longer silently  fails server-side resetting any submitted data to the server copy. 

While working on it I noticed index.php still has all of it's serverside validation logic in place, but currently uses html5 validation. The test page can't use html5 validation and still allow deletes with the way they are currently done. However, all of the serverside logic in edit.php has been cut out so that on a failure, there is no error message and all values are reset back to the server side values. Even with fix #172, deleting down to 1 or 0 tests will still fail silently on server side and reset the form. 

For an easy fix without making something new for the client side, the validation logic that is still in index.php could be put back in edit.php. That way the submit would atleast return the current values instead of resetting the form.

**Comment by jdalton** [comment]
I don't think we'll be tackling this but thanks for the suggestion.
