### ISSUE TITLE
Add unit testing for correctness

### ISSUE THREAD

**Issue by styfle** [mathiasbynens/jsperf.com#174]
I have found myself writing tests to compare performance cross-browser and then realizing the results are moot because IE doesn't work properly. Who cares if IE gets a lot of ops/sec if the result is not correct?

Is there a way to add in some unit testing to make sure the result is correct and drop performance results for that test if that test result is not correct?

Maybe integrate something like QUnit http://qunitjs.com/

**Comment by jdalton** [comment]
Naw, that's out of scope. Devs can add their own asserts.
