### ISSUE TITLE
Client hardware detection

### ISSUE THREAD

**Issue by nCrazed** [mathiasbynens/jsperf.com#176]
I am looking to do a single test across different browsers and client hardware and after a short discussion in #angular.js@Freenode it was suggested that I might want to contribute to this project instead makings something from scratch.

Is hardware detection/consideration something that is desirable for this project? If yes, I would like to discuss what kind of information might be useful in general and how should it be collected? Currently I am thinking either a survey before/after tests or a Java applet to automatically obtain the details to minimise the effort for the visitors.

**Comment by jdalton** [comment]
Hardware detection is a bit out of scope for JSPerf & we're trying to minimize the use of things like Java applets. While hardware can make a difference in overall ops/sec the trend usually matches for a given browser version on varying machines.
