### ISSUE TITLE
Provide a way to account for per-iteration overhead

### ISSUE THREAD

**Issue by hollasch** [mathiasbynens/jsperf.com#178]
Like others, I was surprised to find that there's no way to suspend the timer or otherwise perform untimed setup per iteration. In my case, I was testing array modification, and I (and a colleague separately) ran into the gotcha that our arrays were modified down to zero length, and thus reporting wildly inaccurate timings.

I'd like to have a way to create an empty loop that captures iteration overhead, and them mark that somehow so that JSPerf could then subtract the estimated overhead for n operations.

For example, if the overhead loop takes 37ms per iteration, and a test case takes 38.25ms per iteration (aggregate), then each iteration can be estimated at 1.25ms. Multiple iterations of each test case solve the problem of sub-millisecond timing on the client.

Right now I do all of the above, but I have to do the math myself and squint at the graph to figure out what it should really look like.

**Comment by jdalton** [comment]
> I'd like to have a way to create an empty loop that captures iteration overhead, and them mark that somehow so that JSPerf could then subtract the estimated overhead for n operations.

That's tricky, we investigated doing that but the results came out less crisp than before (the difference of margin of errors creates a higher margin of error).

If all your looking for is which is faster you can always do the same `array.push(someValue)` before the array modification in the test loop. You'll still be able to see which modification method is faster.

**Comment by hollasch** [comment]
Hmmm. In my test (array-shift-multiple), I get a ±1.50% margin of error for the overhead loop, and ±1.43% margin of error for one of the tests (best is 1.07%, worst is 2.67%). Both of these can yield a good estimate for the cost per iteration, at the reported margins of error. A single subtraction of the overhead iteration time from the test iteration time should yield a value with a worst case margin at 2.57% to 4.17%. Further, assuming a fixed overhead loop timing for all tests, the relative ordering of the results should be susceptible only to the reported tests' margins of error, not the overhead loop, an identical result to ordering the results without the overhead computation.

**Comment by jdalton** [comment]
I hear ya, but the margin of error ends up drowning out the cost of the loop overhead.

**Comment by hollasch** [comment]
Oh, I totally agree with respect to loop overhead. I’m talking about
per-iteration setup overhead, which for some operations may even be more
expensive than the code under test. For example, my latest test was a way to
efficiently trim the front 10 values off the front of a 10000 element array
(http://jsperf.com/array-shift-multiple). For this test, I have to clone the
test array each time I do an iteration, otherwise the code just keeps
whittling down the array with each iteration, drastically skewing the
results. In my colleague’s tests, he started with a 100-element array, and
so ended up with a bunch of iterations that work on a 0-element array, which
pretty much ruins the test.

**Comment by jdalton** [comment]
We don't measure the `setup`. The `setup` is not per iteration. A benchmark looks like:

```
<setup>
<start clock>
while (count--) {
<test>
}
<stop clock>
<teardown>
```

You can access the `count` via `this.count` in the `setup` and use that for things like creating the right number of dom elements. I'd be careful creating arrays though as arrays have a max valid length and will throw if you exceed that.

Your colleague's benchmark is bogus.

**Comment by hollasch** [comment]
Right. Setup is done once per set of iterations. Unfortunately, that means that if I want to test a way to shift off the first 10 elements of a 1000 element array, I can't do that in the current framework. Either I create the test array once and then run out of array at iteration 100, or I clone the array inside the test loop and end up accruing the array clone time along with the actual code under test, or I "repair" the array by unshifting back the 10 elements I trimmed, again adding constant overhead to each iteration.

My suggestion is to allow users to do the following:

```
function iterationSetup() {
    var array = _.clone(testArray);
}

function test1() {
    iterationSetup();
    trimMethod1(array);
}

function test2() {
    iterationSetup();
    trimMethod2(array);
}
```

Performance of the empty iteration (within all of the existing margin-of-error framework) is evaluated as for any other code snippet, and other test methods that incorporate the code in the empty iteration are evaluated normally. The only difference is that the overhead cost is subtracted _after_ the body of iterations has been run for each code snippet. Today users can do this with calculator and pencil -- otherwise there's no way to get good performance data for code that modifies inputs, or performs work in addition to 1:1 setup code.

**Comment by jdalton** [comment]
>  or I clone the array inside the test loop and end up accruing the array clone time along with the actual code under test,

That's fine as all tests would have it and you can still determine which snippet is faster. I'm not interested in trying to handle it any further than that.

**Comment by hollasch** [comment]
Understood. Thanks for your work on the site, it's much appreciated!
