### ISSUE TITLE
We need CAPTCHA?

### ISSUE THREAD

**Issue by hemanth** [mathiasbynens/jsperf.com#179]
![](https://cloud.githubusercontent.com/assets/81942/3423682/cdd244b4-ffa4-11e3-9a1d-cb9c3eaf8339.png)

//cc @mathiasbynens

**Comment by mathiasbynens** [comment]
This spammer seems to be using a botnet (every other post is from a different IP). I don’t see an easy/quick way to prevent this, so yeah, looks like we might need to add a Captcha after all. :(

**Comment by mathiasbynens** [comment]
As I really don’t like captchas, I’ve instead enabled [Akismet](https://akismet.com/) on the server. Hopefully that is sufficient.

**Update:** it doesn’t seem to catch all spam yet at the moment, but I’m [actively marking new entries as spam](https://akismet.com/development/api/#submit-spam) so Akismet can block similar posts in the future.

**Comment by hemanth** [comment]
Sweet! They are blocking like `7.5 million per hour` :+1:

**Comment by webberig** [comment]
If you're still considering to add a captcha, take a look at the newest reCaptcha from Google. 
The first captcha out there (that I know of) that doesn't hurt usability...
http://www.google.com/recaptcha/intro/index.html
