### ISSUE TITLE
Specific test consistently hangs browser

### ISSUE THREAD

**Issue by dead-claudia** [mathiasbynens/jsperf.com#181]
This test, upon hitting "Run tests", hangs both Firefox and Chrome like a switch. It is isolated to the process it runs on. I think it might be a Benchmark.js bug, but I'm not sure, and I don't have the immediate ability to test it.

Here's the offending test: http://jsperf.com/bit-mask-property-vs-boolean-property-list2

All test code is syntactically valid.

**Comment by jdalton** [comment]
Not a bug, your `i` eventually becomes `-1` and so the while-loop will never exit causing a lockup.

**Comment by jdalton** [comment]
Fixed the test by initing `i` as `24` in the test loop.
