### ISSUE TITLE
Breach 

### ISSUE THREAD

**Issue by callumacrae** [mathiasbynens/jsperf.com#182]
New browser! http://breach.cc/

It's currently being reported as Chrome—fair enough, it's pretty similar—but it isn't actually Chrome.

This is my user agent:

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.114 Breach Safari/537.36
```

This perf test includes a test ran in Breach: http://jsperf.com/class-vs-data-attrs

**Comment by mathiasbynens** [comment]
Ref. https://github.com/bestiejs/platform.js/issues/61. This is now fixed in Platform.js so we should update the build on jsPerf.

**Comment by callumacrae** [comment]
I thought you were probably using a library, but I couldn't find it.

Awesome :+1:
