### ISSUE TITLE
Show test case names in revision list

### ISSUE THREAD

**Issue by bergus** [mathiasbynens/jsperf.com#184]
I think this would be of great help for popular tests that have many revisions and are contributed to by many different people. It should allow to detect duplicates (test that already have been written by someone else) by skimming over the list of revisions. For that, it should display the (first few?) names of the test cases of a revision in the same line (next to the link) in the list.

**Comment by jdalton** [comment]
Thanks, but I don't think we'll be tackling this anytime soon.
