### ISSUE TITLE
Keep getting 'spam detected' when editing my tests

### ISSUE THREAD

**Issue by YemSalat** [mathiasbynens/jsperf.com#194]
Is there any way to avoid this?

**Comment by jdalton** [comment]
@mathiasbynens
Any update on this? I believe Rick was hit with this too.
He got it as I've seen it by editing a test.

**Comment by mathiasbynens** [comment]
I’ll look into this tomorrow. Sorry for the inconvenience everyone! +@rwaldron

**Comment by mathiasbynens** [comment]
I’ve made some (uncommitted) changes to the live server. Try again and let me know what happens.

**Comment by bnjmnt4n** [comment]
Seems to me like Akismet has a limit to the number of times you can post data with similar content in a limited span of time before marking it as spam. Also @mathiasbynens I didn’t seem to notice a commit where you added spam detection.

**Comment by stefanpenner** [comment]
Is there a way to remove edit count from the spam heuristic?

**Comment by mathiasbynens** [comment]
> Is there a way to remove edit count from the spam heuristic?

I don’t think Akismet has an option to disregard IP checks for successive, similar posts. :(

**Comment by stuartpb** [comment]
Maybe we could just get GitHub authorization as a workaround? So, in order to post a jsperf test, I have to log in with my GitHub account, and random form-submitting spambots don't accidentally post spam to the system.

**Comment by aaaidan** [comment]
This is a pretty bad problem ... it kinda cripples jsperf. Is there anything we can do to help with this? Time, money, testing?

**Comment by mathiasbynens** [comment]
@aaaidan You could work on a patch that adds GitHub OAuth-based login functionality and requires it for adding/editing test cases and comments.

**Comment by stuartpb** [comment]
What about using reCAPTCHA to allow anonymous edits?

**Comment by threehams** [comment]
I've just reproduced this from clicking Beautify Code and Save Test Case within about a second of each other, forgetting that one triggers the other.

**Comment by ghost** [comment]
It should be obvious but a work around is to leave the edit screen open and when it happens create a new test and copy everything from that page.

**Comment by YemSalat** [comment]
We've been using akismet on one of our projects and it seems to be too 'paranoid' sometimes, we are currently looking for another solution for spam control, if we do find a better one that could potentially be used for jsperf - I'll let you know.

**Comment by cshaa** [comment]
:+1: Also affected

**Comment by jrainsberger** [comment]
Happening when I edit this as well: http://jsperf.com/duff-vs-for-loop/

**Comment by briandeheus** [comment]
Yeah this is kinda annoying. +1

**Comment by jdalton** [comment]
@mathiasbynens I thought this was killed?

**Comment by levitation** [comment]
Any workarounds? The message is very uninformative and nothing seems to help.

**Comment by michaelficarra** [comment]
I just got this today and I don't know how to work around it. I've completely changed the tests up to no avail, and I haven't posted a JSPerf in months. What could be triggering it?

**edit:** I fixed it, there was a github issue link in the description that triggered it.

**Comment by zpq2004** [comment]
Still seeing this annoying message today.

**Comment by zbjornson** [comment]
StackOverflow link in description seems to have triggered this 0.o

**Comment by zpq2004** [comment]
I removed the links from description and it works. Thanks very much to zbjorson.

**Comment by dalisoft** [comment]
I have all account, example, GitHub, CloudFlare, Google and other.
Still, jsperf runs CloudFlare captcha. What i need to do to make performance test?
Please help or can you're give me HTML5 version of performance tester?

I removed links from my test case, still runs CloudFlare captcha

**Comment by veleek** [comment]
This is still an issue.  The VERY first submit that I made return Spam Detected! :(

**Comment by connorjclark** [comment]
Spam detected on 1st edit.

This feature really ought to be removed.

**Comment by asselin** [comment]
I'm affected too

**Comment by jacobq** [comment]
#StillAProblem Please let me know if/how I can help. Thanks.

**Comment by hackel** [comment]
Trying to edit this: http://jsperf.com/fast-array-foreach/281 and get "Spam Detected" no matter what.  I even disabled uBlock!  Please don't tell me you need me to enable 3rd party cookies as well.  What is going on here?  If the spam bots have gotten to the point where they can successfully "select all the photos with rivers," we're really in trouble!

**Comment by rconnamacher** [comment]
Still a problem for me too. Every time I try to make an edit, I'm getting "Spam detected" even after going through all that CAPTCHA / detect photos with rivers thing.

**Comment by mathiasbynens** [comment]
This won’t be fixed in the current version of jsPerf but we’re working hard on launching v2 soon. https://github.com/jsperf/jsperf.com

**Comment by susant123** [comment]
I am affected too. Any probable date of v2 release?

**Comment by jeremychone** [comment]
getting the same error. I created the first test, forgot a variable, and now I cannot edit.

**Comment by CarterLi** [comment]
Same here. It's annoying...

**Comment by Azeirah** [comment]
I'm unable to change my test...
Will this "spam detected" go away if I wait, say, a day?

**Comment by GabrielGMartinsBr** [comment]
three days of getting spam detected, please remove this bugged script to let us use the system

**Comment by jdalton** [comment]
I'm closing this issue and snipping it back to @mathiasbynens' comment.
Yes, we know there's problems. No, your complaints won't make it resolved any sooner.
