### ISSUE TITLE
Wrong “fastest” labels

### ISSUE THREAD

**Issue by RubenVerborgh** [mathiasbynens/jsperf.com#195]
A recent test gave me the following result:
- 132,803,732 – fastest
- 132,460,358
- 130,991,488 – fastest

while that should have been
- 132,803,732 – fastest
- 132,460,358 – fastest
- 130,991,488

![screen shot 2014-10-03 at 20 04 37](https://cloud.githubusercontent.com/assets/675313/4510175/d74b992c-4b27-11e4-9b21-bf464eb01ad9.png)

**Comment by jdalton** [comment]
The margin of errors are what make the difference here. The ones highlighted are the fastest discounting their margin of errors.

**Comment by RubenVerborgh** [comment]
Thanks for explaining, but that doesn't explain everything I think. I subtracted the margin of errors:
- 131,223,367
- 130,632,405
- 129,838,762

So seems it should still be A & B.

**Comment by jdalton** [comment]
Hmm, I'll review that bit in the code. Would you share the jsperf test you saw this on.

**Comment by RubenVerborgh** [comment]
It was this one: http://jsperf.com/unknown-hash-key/2

**Comment by jdalton** [comment]
For some insight into our process we [sort based](https://github.com/bestiejs/benchmark.js/blob/40b617a6c50d316e7fdcf39a8bf9032c51a5350c/benchmark.js#L789-L792) on `mean` + `moe` but then run them through [compare](https://github.com/bestiejs/benchmark.js/blob/40b617a6c50d316e7fdcf39a8bf9032c51a5350c/benchmark.js#L1410-L1455) to perform a [Mann-Whitney U test](http://en.wikipedia.org/wiki/Mann%E2%80%93Whitney_U_test) on them.

**Comment by jdalton** [comment]
If you can reproduce this again after your run would you open your web console and do `ui.benchmarks.map(function(b){return JSON.stringify(b.stats,null,2)})` then paste the output into a [gist](https://gist.github.com/) and report back.

**Comment by RubenVerborgh** [comment]
Tried a few times but haven't been able to reproduce…
I suppose the above numbers and percentages are insufficient to make this into a unit test?

**Comment by jdalton** [comment]
> Tried a few times but haven't been able to reproduce…

If you see it show up again then, no worries.

> I suppose the above numbers and percentages are insufficient to make this into a unit test?

Right, we'd need the full stats record to be able to dig into it and see what's up.
