### ISSUE TITLE
Strange Math

### ISSUE THREAD

**Issue by dillonkrug** [mathiasbynens/jsperf.com#198]
Not sure how this could be correct ( 2,754,108 > 2,709,684 as far as I'm aware... )

![screen shot 2014-10-17 at 11 17 52 am](https://cloud.githubusercontent.com/assets/3105014/4682102/36ae7afa-5619-11e4-970a-632d74541a67.png)

**Comment by jdalton** [comment]
Margin of error can play into it. Next time you see something strange take a snapshot of the stats data and report back with it dumped to a gist:

``` js
ui.benchmarks.map(function(b){return JSON.stringify(b.stats,null,2)})
```

Related to #195.
