### ISSUE TITLE
Update JS dependencies

### ISSUE THREAD

**Issue by bnjmnt4n** [mathiasbynens/jsperf.com#199]
Apparently, the last update for Benchmark.js was 3 years ago. @jdalton how about an update?

**Comment by jdalton** [comment]
We've updated jsPerf.com more often then the actual Benchmark.js npm package :D

**Comment by bnjmnt4n** [comment]
But the repo's latest commit is 3 years ago.

**Comment by jdalton** [comment]
Ah I see you're talking about this repo :P

**Comment by jdalton** [comment]
@mathiasbynens has this been tackled?

**Comment by mathiasbynens** [comment]
We use a hacky deploy technique (`/_tmp/`) that updates benchmark.js and the other dependencies. The repo is not up to date when it comes to those deps.

**Comment by jdalton** [comment]
Should we punt until the rewrite?

**Comment by mathiasbynens** [comment]
Yeah, probably. I doubt this repo will get updates.
