### ISSUE TITLE
UX feedback by Hammad Tariq

### ISSUE THREAD

**Issue by mathiasbynens** [mathiasbynens/jsperf.com#2]
Nice work but there are some UX issues.

Say, I am adding a test, the two buttons at the end, Add code snippet and Save test case are confusing. First of all they are so close to each other, first time instead of clicking on Save, I clicked Add code snippet and then I guess there is no way to get rid of it, as it become mandatory and while I had no 3rd test code, I ended up refreshing and giving all my input again.

Add could be a button on the side somewhere and there could be a button to remove extra code snippet if you don't want it. Save test case itself is a bit confusing as newbie will not know what will happen if I save it, I honestly straight away wanted to test my loops, may be it can be renamed as Save & Test .. the other issue is with difference browsers, I tried looking at it (not that hard) but still I am not sure how I can add different browsers to my test case, like at the moment it works for only Chrome, what about if I want to add IE in the test. How do I do that? I have seen people doing it on their tests, maybe there is a degree of difficulty for a newbie to understand how it works, workflow can be a made a bit more smooth.

**Comment by gblazex** [comment]
I personally find this hilarious :)
