### ISSUE TITLE
Add Buffer() class

### ISSUE THREAD

**Issue by binarykitchen** [mathiasbynens/jsperf.com#207]
node.js' Buffer class is very often used and crucial in many tests. Currently `new Buffer()` would result into `Buffer is not defined.`

There are no external libraries out there to include the Buffer class I think (or am I wrong). So I think it would be cool to be able to add those basic classes with Browserify or something like that. I know this request might be far out of the scope. Just wondering here what I can do ...

**Comment by jdalton** [comment]
Hi @binarykitchen! jsPerf allows you to add your own script files which includes a browserified Buffer script.

**Comment by binarykitchen** [comment]
Hmmm, do you know any browserified Buffer script out there I could easily include right now?
