### ISSUE TITLE
Facebook "Like"

### ISSUE THREAD

**Issue by coldhead** [mathiasbynens/jsperf.com#21]
I think a lot of people would like to see a feature where you can "Like" certain tests on Facebook.

Thank you.

**Comment by mathiasbynens** [comment]
Here you go: http://jsperf.com/facebook-share#fb_share

**Comment by coldhead** [comment]
Works great, thanks. +1

**Comment by mathiasbynens** [comment]
> +1

I think you mean “Like”.

**Comment by coldhead** [comment]
It says I need a Facebook account to "Like" :(
