### ISSUE TITLE
Browser scope gets blocked in Chrome

### ISSUE THREAD

**Issue by agrberg** [mathiasbynens/jsperf.com#211]
Chrome enforces more web policies than other browsers so Browser Scope doesn't load. The following is in the console:

```
 Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://jsperf.com" from accessing a frame with origin "http://www.browserscope.org". Protocols, domains, and ports must match.
```

**Comment by Krinkle** [comment]
At the moment https://www.browserscope.org/ is unavailable over HTTPS.

As a result, any tests run are not submitted to browserscope. It works fine when using jsperf.com over plain HTTP. However, user actions are redirected back to HTTPS by jsperf.com (e.g. Beautify code or Save test case). Is that intentional?

**Comment by michalc** [comment]
My errors in Chrome don't mention security. When trying to get https://www.browserscope.org/ urls I get:

```
Failed to load resource: net::ERR_CONNECTION_CLOSED
```

Firefox seems to work fine.

**Comment by mathiasbynens** [comment]
https://code.google.com/p/browserscope/issues/detail?id=356

**Comment by Krinkle** [comment]
@mathiasbynens Could you consider changing jsperf.com to not enforce HTTPS when submitting forms? Even when manually changing urls to jsperf.com to HTTP, it's almost impossible to stay on HTTP.  Perhaps relative urls, so that if you want to use HTTPS and not get graphs, that will still work.

**Comment by mathiasbynens** [comment]
As of today, Browserscope now supports HTTPS (through Cloudflare’s Universal SSL)!

**Comment by jdalton** [comment]
:clap:
