### ISSUE TITLE
Export to node.js/io.js feature

### ISSUE THREAD

**Issue by mscdex** [mathiasbynens/jsperf.com#213]
Many times I see a (non-DOM-related) test on jsperf.com that I would like to test on node.js/io.js, but having to manually write the code to duplicate the test for these platforms is a hassle.

It would be great to have a button on test pages that generates the script for that particular test revision that you can easily run inside node.js/io.js (e.g. you just `npm install benchmark` and then paste the exported script into a file and run it).

**Comment by jdalton** [comment]
Check out [jspm.io](http://jspm.io/) for testing node packages in the browser.
For an example of usage see http://jsperf.com/amp-indexof.

**Comment by mscdex** [comment]
Well I meant code that is not in a package on npm, just random jsperf tests that I can run in node/iojs.

**Comment by jdalton** [comment]
We don't currently have plans to write such a tool. Though would be open to providing feedback & review for someone else wanting to.

**Comment by OrKoN** [comment]
@mscdex I have created a simple tool to fetch and run jsperf.com tests in node: https://github.com/OrKoN/jsperf

**Comment by mscdex** [comment]
@OrKoN Yeah, I ended up writing [`benchd`](https://github.com/mscdex/benchd) awhile back to satisfy my needs :-)
