### ISSUE TITLE
"100% slower" never makes sense

### ISSUE THREAD

**Issue by fresheneesz** [mathiasbynens/jsperf.com#219]
If i'm looking at a test that can do 1 million iterations, vs a test that can do 200, it still says its "100% slower". Can you make those percents meaningful? It should say 5000% slower

**Comment by jdalton** [comment]
Nope, but you can open a PR.

**Comment by fresheneesz** [comment]
@jdalton How bout keeping it open until someone does it? I think you took "can you make..." too personally.
