### ISSUE TITLE
Results breakdown by browser should include platform

### ISSUE THREAD

**Issue by pieroxy** [mathiasbynens/jsperf.com#222]
I've noticed quite a few tests now where results are wildly different on the latest Chrome whether you're running them on Linux, Windows or MacOS. The browserscope graph averages all that into oblivion and looking at it gives in final a wrong impression.

Seeing "Window10 - Chrome35" or "MacOS10.10 - Firefox 35" would be much more helpful.

I have example of tests like these: http://jsperf.com/lzstring-1-4-strings-vs-arrays

strings win all the time on MacOX or Windows8.1 and arrays win all the time on Linux on both Chrome 41 and Firefox 36 ... This is consistent across multiple runs on all platforms but the BrowserScope bars completely hide this fact by averaging all differences and presenting a number that is, in fact, utterly wrong.

**Comment by pieroxy** [comment]
In particular, this [jsperf](http://jsperf.com/javascript-concat-vs-join/2) is making me doubt about the pertinence of this patch for in-browsers lz-string usages.

But now that I understand your issue, I'll try to think of something to mitigate it.

**Comment by jdalton** [comment]
I don't think we'll be tackling this any time soon but we'll keep an eye on the popularity of the request.
