### ISSUE TITLE
URL field when creating comments or tests

### ISSUE THREAD

**Issue by mortie** [mathiasbynens/jsperf.com#223]
I tried entering my website, www.mort.coffee, into the URL field when creating a test. I got the error message: "Please enter a URL". I've tried with a couple of other valid domain names with the new TLDs, and it doesn't seem to accept any of them.

**Comment by mathiasbynens** [comment]
A valid URL contains a scheme.

**Comment by mortie** [comment]
What, you need "http://" or "https://" when entering a URL? I'd argue that's a pretty severe usability issue. I have never before encountered a user interface where you need to specify the scheme when inserting a URL.

**Comment by mathiasbynens** [comment]
That’s how `<input type=url>` works, yes. Note that this is not even a jsPerf issue, it’s your browser (correctly) doing the validation.
