### ISSUE TITLE
Chrome 41 / Win7 - 64bit: Uncaught SecurityError

### ISSUE THREAD

**Issue by gesius** [mathiasbynens/jsperf.com#224]
Chrome 41 / Win7 - 64bit

Uncaught SecurityError: Blocked a frame with origin "http://jsperf.com" from accessing a frame with origin "http://www.browserscope.org". Protocols, domains, and ports must match.

Occurrs after running the test. The Graph from browserscope.org does not show up afterwards instead an ScriptError will be displayed.

Looks similar to me as for the IOS / Safari issue.
https://github.com/mathiasbynens/jsperf.com/issues/204

**Comment by gesius** [comment]
The file https://www.browserscope.org/static/img/logo.png is not available for me via https

_css/main.src.css: Line: 355 --> #bs-logo

**Comment by mathiasbynens** [comment]
https://code.google.com/p/browserscope/issues/detail?id=357
