### ISSUE TITLE
Script Error Mobile Safari

### ISSUE THREAD

**Issue by arb** [mathiasbynens/jsperf.com#226]
Any suggestions as to why [this](http://jsperf.com/collection-perf-native-vs-library) jsperf errors on mobile Safari? I tried connecting my iPhone to my Mac to debug but the error doesn't seem to make it to the console. Also, all the tests appear to finish, it seems like during the reporting phase the error happens.

**Comment by jdalton** [comment]
I'm not sure, I need to sit down on a weekend and dig into this more. I believe this issue is a dup #204.
