### ISSUE TITLE
Use an out of the box code editor.

### ISSUE THREAD

**Issue by SelflessPsychopath** [mathiasbynens/jsperf.com#227]
A trivial ACE integration would make life a lot nicer while using jsPerf.

**Comment by mathiasbynens** [comment]
This can be done in a bookmarklet / user script / browser extension.

**Comment by mhavard999** [comment]
So would you not accept pull requests that implement this?

**Comment by mathiasbynens** [comment]
Personally, I’d prefer to keep jsPerf as simple as possible.

Anyway, this repo is not maintained any longer; jsPerf development has moved to https://github.com/jsperf/jsperf.com. We’re still in the process of recreating the full site so at this point no new features will be added.

**Comment by mhavard999** [comment]
Okay.  The "source on Github" link in the footer points to this repo.  FYI.
