### ISSUE TITLE
Browserscope box has different results than the test run

### ISSUE THREAD

**Issue by BigFav** [mathiasbynens/jsperf.com#230]
When I run this test for Firefox 38, there is a conflict in result values as shown in this image:

![jsperf_differing_op_nums](https://cloud.githubusercontent.com/assets/2354042/7674641/774338c0-fce1-11e4-993b-8ab12ffbc8d7.png)

All of the results were run by me, and had the same problem (I also ran the Chrome cases, and those worked fine). If it is difficult to see, the highlighted case has 3,068,574 ops/sec, whereas it says 7,190,578 ops/sec above highlighted in green (you may need to open it in a new tab and zoom in).

The link is here: http://jsperf.com/array-direct-assignment-vs-push/122

I apologize in advance if this is the wrong place for this issue, or if it is a duplicate.

**Comment by jdalton** [comment]
The results are recorded with their lower end of the margin or error. I believe browserscope also displays the mean (or some mean-like computation) of the total results.

**Comment by BigFav** [comment]
All of the results are like this, and I know because I ran it all 4 times. If it were the mean, then it should be ~7 million as it is highlighted in green.

**Comment by BigFav** [comment]
Here, I re-made the jsperf, so that you can see this error happens on only one run. Also note that not only is the "Direct assignment (literal array with length set)" wrong, but so is the "Direct assignment (empty literal array)". 

![jsperf_again_on_one_run](https://cloud.githubusercontent.com/assets/2354042/7675228/ada44eaa-fcea-11e4-8fcd-476c58688bc1.png)

Is discrepancy expected behavior? I understood your response to be talking about the 4 times I had previously run it.

The link is here: http://jsperf.com/jsperf-firefox-err
