### ISSUE TITLE
browserscope downtime

### ISSUE THREAD

**Issue by paulirish** [mathiasbynens/jsperf.com#231]
Over the past 30 minutes no data has loaded from browserscope. I don't know who's running that site these days, but I would imagine its infrastructure is lagging. 

Is there anyone who can kick it back into good behavior?

Also, Something for @maxbeatty to keep in mind for v2. 

![image](https://cloud.githubusercontent.com/assets/39191/8021421/4216da76-0c54-11e5-8852-d5a45f05204e.png)

**Comment by jdalton** [comment]
If you're viewing the site with https it causes that in Chrome. See #211.

**Comment by paulirish** [comment]
oh.gotcha.. thanks!

 i didnt choose https so i guess that's what google search gave me. 

If that's the case can we update this error message in BScope to communicate this workaround?

**Comment by mathiasbynens** [comment]
https://code.google.com/p/browserscope/issues/detail?id=356

**Comment by jdalton** [comment]
Closing as a Browserscope issue.
