### ISSUE TITLE
Can't handle UTF-8 in setup function

### ISSUE THREAD

**Issue by coolaj86** [mathiasbynens/jsperf.com#232]
See https://jsperf.com/utf-8-acceptance-test

``` js
var str "I'm a ☢ ☃ who speaks 中国语文, loves 𝄢 guitar, and plays in 💩!"
```

becomes

``` html
<script>
  Benchmark.prototype.setup = function() {
    var str = "I'm a ☢ ☃ who speaks 中国语文, loves 
  };
</script>
```

I changed things a little bit to not include 4-byte utf8 chars, but still couldn't run all of my intended tests:
https://jsperf.com/utf-8-encoding-decoding

**Comment by coolaj86** [comment]
In case you can't actually see those characters, here are some others:

💩    𐑶    𐐦    🃏    𝄢    𩶘

```
💩    𐑶    𐐦    🃏    𝄢    𩶘
```

**Comment by bnjmnt4n** [comment]
Related to #93.
