### ISSUE TITLE
verification of working code / unit tests

### ISSUE THREAD

**Issue by EphDoering** [mathiasbynens/jsperf.com#233]
I'm not sure how this could be be implemented, but I was looking for some fast base64 conversions and some of the tests produced incorrect results, but there was no easy way to tell that.

If there was a way to verify the output results (not in the timing loop) of even one test that could be very valuable as then when a new "faster" test that produces inconsistent results it could be displayed, maybe with a little warning icon.

for example I hacked together a sample on the base64 test:
http://jsperf.com/base64-to-uint8array/16

I don't think this is a good ui or coding practice, but I think it does highlight the use case.

**Comment by jdalton** [comment]
Hi @FrederickDoering! That's outside the scope of jperf. Devs are free to add any number of checks before their snippet to ensure expected results.
