### ISSUE TITLE
jsPerf.com down

### ISSUE THREAD

**Issue by tomByrer** [mathiasbynens/jsperf.com#234]
http://jsperf.com/
`Website Disabled`
:sob:

**Comment by jdalton** [comment]
See https://github.com/jsperf/jsperf.com/issues/18.

**Comment by reverofevil** [comment]
@jdalton The last message in that thread says "I’ve temporarily re-enabled jsPerf with Google reCAPTCHA implemented. Let’s see how this goes." but it's been two weeks since then and the website is still down. What's going on?

**Comment by mathiasbynens** [comment]
Somehow spam _still_ started getting through after a while, indicating this is in fact manual spam (unless someone managed to break Google ReCaptcha already, which I highly doubt).
