### ISSUE TITLE
Unable to create or execute tests

### ISSUE THREAD

**Issue by rex** [mathiasbynens/jsperf.com#235]
Hello JSPerf Team,

Just wanted to file an issue to ensure that someone had visibility into this.

I tried a number of times to create a new test case but it failed each time without any indication as to why. I opened the inspector and got the answer:

![Missing JS File](http://i.imgur.com/Xysuy3T.png)

Okay, no new test case. Maybe I can use a similar one. Went to a different test URL and no dice either. 

![Missing JS, UI not defined](http://i.imgur.com/MzYc7KP.png)

Let me know if you need any more information than that! Have a great day!

**Comment by mathiasbynens** [comment]
Fixed.

**Comment by rex** [comment]
@mathiasbynens Works like a champ! Thank you so much for fixing it so quickly! :smile: :rocket:
