### ISSUE TITLE
Firefox and IE don't show up in Browserscope results by default

### ISSUE THREAD

**Issue by rgrove** [mathiasbynens/jsperf.com#24]
The Browserscope charts seem to be filtering out Firefox and IE results (possibly others, these are just the ones I noticed) by default. You have to click the "all" link next to "Filter" in order to see these browsers.

This seems like a very strange default to me. Bug or intentional?

**Comment by mathiasbynens** [comment]
We should either use the _All_ filter as the default, or continue to use _Popular_ but have it change to _All_ when the current browser isn’t listed there.

**Comment by jdalton** [comment]
I think we will simply use `all` to avoid additional requests to BS servers.
