### ISSUE TITLE
Details about machines

### ISSUE THREAD

**Issue by baxissimo** [mathiasbynens/jsperf.com#25]
It would be nice to know a little more about the machines that ran the tests in addition to just the browser version.  If I'm running IE9 on a 5 year old laptop, it's not exactly apples-to-apples with chrome14 on a brand new desktop.  Also with new browsers starting to HW accelerate canvas operations, what GPU you have also matters and whether GPU acceleration is actually enabled.  You can't tell these things from just a browser version.

At the very least it would be nice to know something about the basic performance of a machines CPU.  You could perhaps do something more with a Java plugin to figure some of that out?  At least the performance of Java execution should be a little more uniform than JS across a wide variety of machines.  Then you could attach that benchmark number to every result..  And maybe have a graphing option to normalize results based on that standard benchmark.

I realize it would be tough to get right, but it would definitely improve the ability to use jsbench as a crowd-sourcing benchmark tool.

**Comment by jdalton** [comment]
We currently can't do this with Browserscope. Browserscope does return the median of the result data.
