### ISSUE TITLE
jsperf.com down

### ISSUE THREAD

**Issue by broofa** [mathiasbynens/jsperf.com#255]
![image](https://user-images.githubusercontent.com/164050/93482471-9a9cf200-f8b4-11ea-8b73-d46a08f62b12.png)

![image](https://user-images.githubusercontent.com/164050/93482274-63c6dc00-f8b4-11ea-983f-ba6d1b92dd9d.png)

**Comment by Rabbitzzc** [comment]
me too!
Has anyone fixed it ?

**Comment by broofa** [comment]
@mathiasbynens  ?

![image](https://64.media.tumblr.com/22e6d51090acf89a34ddbd1ad1e1772b/tumblr_p2t35bQYJw1wmzeljo1_400.gif)

**Comment by cyfung1031** [comment]
@mathiasbynens  Is this project ended?

**Comment by Rabbitzzc** [comment]
> @mathiasbynens Is this project ended?

I think so..

**Comment by broofa** [comment]
[Closing out issues I authored that appear to be stagnant.]
