### ISSUE TITLE
Add a button to run many benchmarks

### ISSUE THREAD

**Issue by baxissimo** [mathiasbynens/jsperf.com#26]
I see that most tests on jsperf don't have a whole lot of results.
One of the awesome things about jsperf is that anyone can contribute results.  But I don't see a lot of that happening because you have to dig down into each one.
How about tapping into people's willingness to help each other out by putting a big button on the front page that runs a selected set of benchmarks that could use input from the browser the visitor is running?   Perhaps test writers could opt in to having their tests included in this crowd-sourcing effort.   Some people may prefer to keep their tests mostly under their own control, so that they know the machine specs behind the results.

**Comment by mathiasbynens** [comment]
This is one of the most popular feature requests. This is gonna use up a lot of bandwidth, but I’ll see what I can do…

**Comment by mathiasbynens** [comment]
Moved to #54.
