### ISSUE TITLE
Preview without saving?

### ISSUE THREAD

**Issue by baxissimo** [mathiasbynens/jsperf.com#27]
It would be nice if it were possible to preview without saving so you don't end up saving tests that are just completely broken.

**Comment by mathiasbynens** [comment]
This is why we have the “published” checkbox.

![](http://i.imgur.com/WhydV.png)

Unpublished tests won’t appear in any search listing — you won’t see them unless you know the URL.

**Comment by baxissimo** [comment]
Ah, ok.  I unchecked that once and then didn't notice it after that.  I guess I was expecting it to be sticky.

**Comment by mathiasbynens** [comment]
Sticky as in, for all test cases you create after that?

**Comment by baxissimo** [comment]
Yes.  I suppose it just seems odd to me that it's not the default to first have a chance to preview before making a test go live.  It makes it so easy to publish a non-working test.  And then there's no way to un-publish a mistake, as far as I could tell.  It just seems like the wrong UI to me to have a check box that decides whether it will be public or not at the time of first creation.  Even wikis usually have a two step preview, then commit flow, and that's not even executable code.

**Comment by mathiasbynens** [comment]
> […] there's no way to un-publish a mistake, as far as I could tell.

You can just `/edit` the testcase and uncheck the checkbox.
