### ISSUE TITLE
Remove the preparation code JS (replaced by `setup`)

### ISSUE THREAD

**Issue by mathiasbynens** [mathiasbynens/jsperf.com#28]

**Comment by jdalton** [comment]
This may be tricky... I will have to think.

**Comment by mathiasbynens** [comment]
No it won’t. I’ll just remove the preparation JS field, and replace it with the `setup` field.

I don’t think you’ll have to change a single thing :)

**Comment by jdalton** [comment]
Go go JSPERF!!! 9000++

**Comment by mathiasbynens** [comment]
BOOM! http://twitter.com/jsprf/status/123098413536509952
