### ISSUE TITLE
Double-clicking previous/next arrow in chart legend selects text

### ISSUE THREAD

**Issue by kornelski** [mathiasbynens/jsperf.com#29]
I'd expect multiple successive clicks on arrows next to chart's legend ("`< 1 / 4 >`") to scroll the legend quickly, but browser takes over and starts selecting text. A missing `preventDefault()`?

**Comment by jdalton** [comment]
This would be a google visualization bug. Please post on the [google visualization bug tracker](http://code.google.com/p/google-visualization-api-issues/issues/list).
