### ISSUE TITLE
There should be a "Remove Snippet" button

### ISSUE THREAD

**Issue by davidmurdoch** [mathiasbynens/jsperf.com#3]
Our keyboards have a backspace and delete button because we all suck at getting things right the first time.

Can we have a "Remove Snippet" button for each snippet please?

**Comment by mathiasbynens** [comment]
This is a longstanding issue and I _really_ need to implement this asap. Thanks for the reminder :)

**Comment by mathiasbynens** [comment]
Fixed :) For instructions, I’ll just quote http://twitter.com/jsprf/status/38621834333261824:

> You can now delete specific tests when editing a test case. Just clear the ‘title’ and ‘code’ fields for the snippet you want to remove.

**Comment by laukstein** [comment]
It is no more working, see #161.
