### ISSUE TITLE
colors and bars

### ISSUE THREAD

**Issue by nizzy** [mathiasbynens/jsperf.com#30]
I have 3 suggestions.

1) bars' height is too tiny for many browsers test.
2) blue and baby blue are too close to each other, hard to distinguish them.
3) add color legend to left column of test table as well.

thank you

**Comment by jdalton** [comment]
> 1) bars' height is too tiny for many browsers test.

I donno how much we can tweak that as we use the Google visualization api for charts.
You can always switch to the table view or other views if bars are hard to read.

> 2) blue and baby blue are too close to each other, hard to distinguish them.

We use the auto generated colors of the Google visualization api but we can manually specify them too. I will look into this.

> 3) add color legend to left column of test table as well.

There should be a legend on all charts that have colors.

**Comment by nizzy** [comment]
At least you got back to me. Thank you very much.

is your site mobile compatible? it would be nice if it is.

take care.
Nizam

**Comment by jdalton** [comment]
> is your site mobile compatible?

Yes, jsPerf runs on a variety of mobile devices.

**Comment by nizzy** [comment]
Cool. Haven't tried it yet, but I use your site a lot recently for my mobile app at Skype.

thanks

**Comment by jdalton** [comment]
Closing as I likely won't get around to defining anything beyond its default colors.

**Comment by nizzy** [comment]
Sure, John, I understand.

Thanks
Nizzy

On Mon, Dec 12, 2011 at 12:05 AM, John-David Dalton <
reply@reply.github.com
