### ISSUE TITLE
Protection of revisions

### ISSUE THREAD

**Issue by JamieMason** [mathiasbynens/jsperf.com#31]
Please close if I'm wrong about this, but I'm pretty sure I've had this happen to me.

I create a revision for a test - spend quite some time running it on all kinds of browsers, then someone (rightly) wants to contribute, so they go to edit - but a new revision isn't made, the same one is updated and all the test results are cleared out.

Could it be made that if a different person comes to edit a test suite, that it **always** results in a new revision?

Thanks.

**Comment by mathiasbynens** [comment]
Uhm, what you describe is how it’s intended to work right now. You can only edit test cases without creating a new revision if you’re the test case / revision owner (determined through session cookies). No one else should ever be able to edit your test case.

Is this broken for you?

**Comment by JamieMason** [comment]
I can't find @jdalton's reply but in response to [this tweet](https://twitter.com/#!/GotNoSugarBaby/status/122323244056444928) John said he had edited a test for me which was giving skewed results. When I came to it the history of tests was gone.

I'm happy to close this and reopen if it happens again, when I can give more detail.

**Comment by mathiasbynens** [comment]
@jdalton and me are the only two people with admin rights on jsPerf, meaning we can edit any test case we want without creating a new revision. Editing a test case resets its Browserscope results.

Rest assured regular users will never be able to edit/overwrite your stuff. :)

**Comment by jdalton** [comment]
@JamieMason When an edit is done the Browserscope history is also cleared _(in case the changes invalidate the previous recorded perf measurements)_.

**Comment by JamieMason** [comment]
ahh! that makes sense, cool - I'm happy now, thanks :)
