### ISSUE TITLE
Auto-repeat tests

### ISSUE THREAD

**Issue by JamieMason** [mathiasbynens/jsperf.com#34]
Could you consider adding a checkbox or something which lets you keep re-running the tests once the suite has completed? So I can start up a lot of browsers and leave them running, collecting data.

At the moment I time how long my suite takes to run, then add the below to the preparation code;

```
window.repeatTest = setInterval(function ()
{
    $('#run').trigger('click');
}, 40 * 1000);
```

Thanks

**Comment by mathiasbynens** [comment]
Note that for accurate results you should always keep the window + tab of a running test open and focused — running tests in multiple browsers at the same time is bound to mess things up.

That said, I suppose we could allow something like `#repeat=123` in the URL, which would keep on repeating the test 123 times.

**Comment by JamieMason** [comment]
Thanks, yeah I think I need to be more patient in getting test data, but that will help thanks.

**Comment by jdalton** [comment]
Opening a ton of browsers probably isn't good for system memory and could affect other results.
We also don't want to hammer Browserscope unnecessarily.
