### ISSUE TITLE
Setup & lexical scope

### ISSUE THREAD

**Issue by bhk** [mathiasbynens/jsperf.com#37]
Since setup and teardown snippets are placed in separate functions (distinct from each other and from the test snippets), data shared with the test snippet must use a global variable.  In many VMs access to global variables can be slower than access to lexically scoped variables, distorting measurements for snippets that use variables initialized during setup.

Workarounds are possible, but they are ugly and decrease the quality of the measurement:

http://jsperf.com/current-time

One solution would be to define the iteration functions (and teardown) within the lexical scope of the setup function.

**Comment by jdalton** [comment]
The setup and tear down are actually [compiled into the test loop](http://benchmarkjs.com/docs#Benchmark:setup) so the variables defined there are in fact local to the test loop.

**Comment by jdalton** [comment]
The issue you are seeing is because the compiled code is exiting early caused by your `return` statement in the test. This causes it to drop to the fallback method which does not compile and so setup/teardown act as separate methods.

**Comment by jdalton** [comment]
I [patched Benchmark.js](https://github.com/bestiejs/benchmark.js/commit/81098d84afb4d1cbc0a25facaf6e4fd538ab8e9d) to compile tests even when exiting early do to a rogue `return` statement.
