### ISSUE TITLE
Ability to group test case results 

### ISSUE THREAD

**Issue by mikesherov** [mathiasbynens/jsperf.com#39]
Only real way to explain what I mean here is an example: http://jsperf.com/cssprops

This perf tests jquery vs. a patched version of jquery for 3 different scenarios. When the test is run, all of the perf numbers are scored and reported relative to each other. However, what I'd really like to know is how scenario A performs with jquery vs. patched, scenario B performs jquery vs. patched, etc...

I know I could write 3 different perfs for this, but I'd like to be able to post one url and say: "hey, look how my patch performs against the current library".

**Comment by jdalton** [comment]
I believe this would be handled by #58 and #59.
