### ISSUE TITLE
Get rid of single-space indents

### ISSUE THREAD

**Issue by mathiasbynens** [mathiasbynens/jsperf.com#40]
Seriously WTF is up with those‽

**Comment by mikesherov** [comment]
I've been looking at the code for the past few hours, and in my brain saying "TABS PLEASE". What format should I be using for spacing?

**Comment by mathiasbynens** [comment]
Please use tabs. I’ll change the existing code eventually :)

**Comment by jdalton** [comment]
double space FTW _(looks better in github too)_ #bikeshed
