### ISSUE TITLE
what's the deal with _inc/contrib/?

### ISSUE THREAD

**Issue by mikesherov** [mathiasbynens/jsperf.com#41]
Is that directory used for anything, or is it a red herring? Seems like unnecessary cruft to have to wade through...

**Comment by janmoesen** [comment]
It's actually Geshi's contrib directory.

**Comment by mikesherov** [comment]
@janmoesen, right, but it doesn't seem to be used for anything. Having the directory plus all the code inside it there makes it harder to see what the dependencies actually are.

**Comment by janmoesen** [comment]
True. I figured it was some licensing issue, but then the `docs` directory has been removed, too. Probably some leftovers. Mathias, can these be safely deleted? They do not appear to be used.

**Comment by mathiasbynens** [comment]
It's part of GeSHi; not sure if it’s really needed or not.

**Comment by mikesherov** [comment]
None of the code references it. I deleted it on my local and it seems
to work fine. I'll see if I can get a more definitive answer.

On Oct 30, 2011, at 11:53 AM, Mathias Bynens
reply@reply.github.com
wrote:
