### ISSUE TITLE
Cleanup .htaccess of root

### ISSUE THREAD

**Issue by jdalton** [mathiasbynens/jsperf.com#53]
I see [some junk](https://github.com/mathiasbynens/jsperf.com/blob/master/.htaccess#L31-38) in the .htaccess file that could be removed

**Comment by mathiasbynens** [comment]
Removing those lines would break existing links to the old URLs.

**Comment by jdalton** [comment]
comment that they can be removed for those cloning the project _(the ones that can be removed)_

**Comment by jdalton** [comment]
Related to #55
