### ISSUE TITLE
compatibility test before runing tests.

### ISSUE THREAD

**Issue by ashi009** [mathiasbynens/jsperf.com#56]
Some tests require certain browser feature. In this circumstance jspref doesn't have a mechanism for this.

**Comment by mathiasbynens** [comment]
Why not just add a note to the “description” field? Works for me.

**Comment by ashi009** [comment]
Here is the thing, if I have 4 tests, 3 using lib to implement the feature required (as a fallback of the native implementation, eg. jquery.$ to  querySelector), and 1 using the browser's native implementation. I have to  separate the test to 2 different test sets for situation, otherwise I can't  get the result on those ancient browser.

**Comment by jdalton** [comment]
For browsers that don't support a specific method you can always add a shim w/ a note about specific browsers or just let it error and the results for that test won't be posted.

**Comment by ashi009** [comment]
Some js feature requires this or it will result in eg. for each (var value in object) will result in a global script syntax error on browsers except Firefox and no test is runnable.

**Comment by jdalton** [comment]
I think this is outside the scope of jsPerf and can be handled by wrapping parts of the prep code in a try-catch or letting the specific benchmark fail.

**Comment by ashi009** [comment]
Try catch will fail in this case, an syntax error won't be parsed by script engine so try catch won't catch it as an exception. If we execute the test code in an eval statement it will return an exception on syntax error. So we can put each test section in an eval statement like: 

``` js
try{
 var test1 = eval('function test1() {for each (var x in y) x++}');
} catch(e) {
}
```

And then execute the responding test (test1 in this case), and this won't affect  performance at all.

**Comment by jdalton** [comment]
I added `onerror` hooks to jsPerf:
https://github.com/bestiejs/benchmark.js/commit/4524fd54b28e9c6edac8c0aa31464cea67bef261#L1R680
