### ISSUE TITLE
Filtering by tests and relative graphs 

### ISSUE THREAD

**Issue by madrobby** [mathiasbynens/jsperf.com#57]
I'd love to be able to filter by individual tests (e.g. show only graph for tests 2, 4 and 5) and the ability to normalize the graphs so that each browser results is "streched" all the way, when you're only interested in relative differences.

**Comment by jdalton** [comment]
Can you split this into 2 issues please. Thanks :D

**Comment by mathiasbynens** [comment]
I’ve filed these as separate feature requests: #58 and #59. Thanks!
