### ISSUE TITLE
“My tests”

### ISSUE THREAD

**Issue by mathiasbynens** [mathiasbynens/jsperf.com#63]
https://github.com/mathiasbynens/jsperf.com/blob/master/_tpl/tpl-inc/foot.tpl#L4-6

@cinsoft says it doesn’t work for him, so check that out…

**Comment by david-mark** [comment]
Yeah, if I go to the root page, it fills in the login info (or at least I think it does, perhaps the browser is doing). But I don't have the "My Tests" link (at least until I add a new test).

**Comment by mathiasbynens** [comment]
The form auto-filling is done via JavaScript (the data is stored in `localStorage`). The link, however, is generated in the back-end based on the session data.

**Comment by david-mark** [comment]
Aha! :)

So you need some sort of "login" form in addition to the "add test" form. Or perhaps a search by user name.

Thanks!

**Comment by NV** [comment]
> So you need some sort of "login" form

+1

How do I login? Post dummy test?

**Comment by david-mark** [comment]
> How do I login? Post dummy test?

That's what I was getting at.

**Comment by jdalton** [comment]
At the moment we don't have plans to create a login system.
