### ISSUE TITLE
jsPerf should email/tweet me a link to my tests whenever a new browser version is released so I can run them again for comparison. 

### ISSUE THREAD

**Issue by jdalton** [mathiasbynens/jsperf.com#66]
Forwarding a feature request from Twitter:

> **@craigpatik**:
> @jsprf should email/tweet me a link to my tests whenever a new browser version is released so I can run them again for comparison

See: http://twitter.com/craigpatik/statuses/149631672504164352

**Comment by mathiasbynens** [comment]
I respectfully disagree. It’s easy enough to [look up your own tests](http://jsperf.com/faq#author-feed) and re-run them when needed.

Currently we’re only using the user-provided email addresses for Gravatars, and that’s about as far as I’d like to go. Even if you enter an address that isn’t your own, no real harm is done. (At most, you could impersonate someone else on jsPerf, but that’s it.) If we start using user-provided email addresses for automated mailings, we’d have to implement validation through confirmation emails, and it just doesn’t seem worth it.

**Comment by jdalton** [comment]
Ya, no worries.
