### ISSUE TITLE
Search through init/setup/teardown/test code as well

### ISSUE THREAD

**Issue by mathiasbynens** [mathiasbynens/jsperf.com#67]
```
<divya> for e.g. this shittily named testcase does not show up when searching for “hogan” http://jsperf.com/t-bench2/6
```

**Comment by mathiasbynens** [comment]
Workaround is to just [use Google](http://www.google.com/search?q=site%3Ajsperf.com+hogan).

**Comment by jdalton** [comment]
Searching through `setup` and `teardown` could cause a lot of noise in the results too. Poor benchmark names and poor benchmarks kinda come with the territory.

**Comment by mathiasbynens** [comment]
@jdalton Good point; that’s exactly why I currently only search through test title and description. (Also, laziness.)
