### ISSUE TITLE
“My tests” slugs buggy

### ISSUE THREAD

**Issue by mathiasbynens** [mathiasbynens/jsperf.com#68]
http://twitter.com/inkel/status/153962620309876737

To reproduce, enter “Leandro López (inkel)” as author name, and check the “My tests” link at the bottom. It points to http://jsperf.com/browse/leandro-lpez-inkel

Looks like a `slug()` problem…

**Comment by janmoesen** [comment]
Sounds like `iconv` not behaving. See if setting the locale (`setlocale`) to `en_US` in the bootstrap makes it work.

**Comment by mathiasbynens** [comment]
`setlocale(LC_ALL, 'en_US')` seems to fix it. Thanks, @janmoesen!
