### ISSUE TITLE
Tweak “Add code snippet” text 

### ISSUE THREAD

**Issue by mathiasbynens** [mathiasbynens/jsperf.com#69]
http://twatlr.com/thread/159919759872360448

> Your "Add Code Snippit" button means "Add test"
> "Save Test Case" should be named "Proceed to run". You could label the snippits "Snippit 1" etc. instead of "Test 1" Match nouns.

**Comment by devinrhode2** [comment]
Yeah, to clarify beyond 140 chars, whether the code snippits are labeled as "Snippit x" or Test 1" the button to add a test/snippit should use the same exact noun. If you enter two tests, and you want to add a test, the button to add a test should f'n say "Add test" and not refer to them as "Snippits"

Alternatively, the tests can be instead labeled as Snippits, and then when you want to add a snippit, the button is labeled exactly so.

**Comment by jdalton** [comment]
I will take this issue.

**Comment by jdalton** [comment]
Closing as stale.
