### ISSUE TITLE
Add support for `base` tags in preparation code.

### ISSUE THREAD

**Issue by jdalton** [mathiasbynens/jsperf.com#72]
Currently some links on the page will break if a user adds their own `base` element to the page. We should fix that by using absolute urls for links.

**Comment by mathiasbynens** [comment]
It’ll always be possible to “break” a webpage that allows you to enter arbitrary HTML + JS in it. I don’t think this is a real issue.

**Comment by jdalton** [comment]
This is how I had to get around the issue:

``` js
var base = '//dl.dropbox.com/u/513327/allyoucanleet/post/10/test/js';
var scripts = 'array audio bugs css dates dom events features form function graphics json object script strings video';

document.write(
  (
    '<script src="base/has.js"><\/script>' +
    scripts.replace(/\w+/g, '<script src="base/has/$&.js"><\/script>')
  ).replace(/base/g, base)
);
```

**Comment by jdalton** [comment]
> It’ll always be possible to “break” a webpage that allows you to enter arbitrary HTML + JS in it. I don’t think this is a real issue.

Sure but I wasn't setting out to "break" the page. The base tag has legit uses for mockups and is pretty easy for us to support with a few find/replace in the site code.

**Comment by mathiasbynens** [comment]
We’d be adding complexity to 99% of all pages to accomodate for 1% of all use cases, while said use case can easily be fixed by just using absolute URLs in the preparation code (or by using JS to add them). I don’t really see the point.

**Comment by jdalton** [comment]
It makes jsPerf more robust at relatively little cost.

**Comment by jdalton** [comment]
>  99% of all pages to accomodate for 1%

Benchmark.js/Platform.js support Safari 2.0.0 your argument is invalid.

**Comment by jdalton** [comment]
The [pull request is here](https://github.com/mathiasbynens/jsperf.com/pull/74).
