### ISSUE TITLE
Add some way to identify related / duplicated tests

### ISSUE THREAD

**Issue by Arcnor** [mathiasbynens/jsperf.com#76]
Looking at the popular list right now, I can see about three test cases that tests while is better to use caching or not when doing a "for" loop.

I know the tests maybe are similar, but not equal, but when searching for a specific feature, browsing similar tests (or avoiding to create new ones) could be a benefit, IMHO.

Maybe adding a button for people to identify them and marking as duplicated or related could improve the site.

Just my $0.02

**Comment by jdalton** [comment]
We don't plan on having a voting system at this time. But it's something that has been requested more than a few times. We will keep brainstorming. Thanks.
