### ISSUE TITLE
Allow hiding of some browsers in the bar graph

### ISSUE THREAD

**Issue by ExtAnimal** [mathiasbynens/jsperf.com#77]
Because the super speed of Chrome means that you cannot hover IE6 graphs to even see their results! You sometimes get a 1 pixel bar which does not event react to mouseover.

Either that, or stretch the bars to show _relative_ results. We're not comparing browser performance but code performance.

**Comment by jdalton** [comment]
You can always switch to the `table` view to see all info when Chrome starts choking-out other browsers.
But filtering is technically doable so, i'll mark this as a feature request.

**Comment by jdalton** [comment]
I will expose the chart data via `ui.browserscope` so devs can access an manipulate it.
