### ISSUE TITLE
JSPerf tests needs organization

### ISSUE THREAD

**Issue by PlNG** [mathiasbynens/jsperf.com#78]
Right now, the way things are, the tests are just a flat out mess.  The site, in my view, needs a new way to represent how the tests are made.  The latest edit should be the best edit for that particular test. I have some concerns of people conducting edit wars (sorry, no evidence of this) and flat out hijacking what a test was originally written for to test their own cases (just look at most written tests).  If someone decides to base an edit on an earlier written edit and publishes that, then it becomes the latest edit and the linear system breaks down because someone made a fork/branch of a test.

A tree based system would be a good step forward, a github network graph style system would be the best.

Separate sections / searches for library testing and vanilla js would be great.  I see too many JQuery tests when looking for a simple method test.

**Comment by jdalton** [comment]
There have been suggestions for some kind of voting system to handle test quality. We will need to brainstorm. Thanks.
