### ISSUE TITLE
Overall average result

### ISSUE THREAD

**Issue by staabm** [mathiasbynens/jsperf.com#81]
The current view of Browserresult show perfectly how fast/slow a test is in a specific browser.

It would be cool if there would be an average result of all browsers, currently shown in the Browserresult table (comparing the fastest test with the others).

Something like:

```

Chrome 18: 
    test1: 800 ops/sec
    test2: 450 ops/sec
    test3: 250 ops/sec

IE 10: 
    test1: 300 ops/sec
    test2: 250 ops/sec
    test3: 250 ops/sec

FF 9: 
    test1: 700 ops/sec
    test2: 350 ops/sec
    test3: 250 ops/sec

OVERALL:
   test1 is 5,8 times faster than test2
   test1 is 1,8 times faster than test3

```

**Comment by tomByrer** [comment]
You can do that now with the "Table" link/tab, though you do have to copy/paste into a spreadsheet.
BrowserScope has an API to play with... http://www.browserscope.org/api

**Comment by jdalton** [comment]
The "Pie chart" view will show you the overall fastest browsers which is close. At the moment we don't have plans to expand the API. There have been requests to perform calculations on the data so I will expose that via the `ui.browserscope` object.
