### ISSUE TITLE
Safari for Windows

### ISSUE THREAD

**Issue by Mottie** [mathiasbynens/jsperf.com#82]
After running [my test](http://jsperf.com/read-innerhtml-vs-innertext-vs-nodevalue-vs-textcontent) in Safari for Windows, browser scope attempts to update itself, but instead opens a new tab to http://www.browserscope.org/beacon/agt1YS1wcm9maWxlcnINCxIEVGVzdBivnvIQDA showing this error:

>  CSRF Error - Need csrf_token in request.

**Comment by mathiasbynens** [comment]
Sounds like a Browserscope issue. /cc @elsigh

**Comment by elsigh** [comment]
This could be some P3P issue, but who knows.. basically that means that the post data didn't include the CSRF token. Hard to debug without firing up something like WireShark and whatnot. As windows for safari is so unpopular, I doubt I'll get to it soon however.

**Comment by Mottie** [comment]
No worries, I only use Safari for WIndows for testing.
