### ISSUE TITLE
Opera for Windows crashes

### ISSUE THREAD

**Issue by Mottie** [mathiasbynens/jsperf.com#83]
When trying to run any jsperf tests in Opera the browser completely locks up and closes the window.

This occurred in my previous version, I forget the exact version number, of Opera and even after updating it to 11.64 with no plugins.

> Version 11.64 
> Build 1403 
> Platform Win32 
> System Windows 7 
> XHTML+Voice Plug-in not loaded
> 
> Opera/9.80 (Windows NT 6.1; WOW64; U; en) Presto/2.10.229 Version/11.64

It may have something to do with BrowserScope since the home page runs without any issue. But opening any test case it appears the page layout is in tact, but the frame is missing just before crashing.

**Comment by mathiasbynens** [comment]
It may also have something to do with Benchmark.js or the nanotimer Java applet (which is only loaded for test pages). /cc @jdalton

**Comment by jdalton** [comment]
Try loading the page with the hash `#nojava` to load with the applet disabled.
