### ISSUE TITLE
No BrowserScope OS/CPU listed

### ISSUE THREAD

**Issue by tomByrer** [mathiasbynens/jsperf.com#84]
Not sure if this is out of scope, but I just noticed that the Operating Systems & CPU families are not displayed &/or collected by the tests.

Occasionally different builds for different platforms will act different.

Intel CPUs have more piplines than AMDs   For both manufacturers, each generation has improvements with math functions on a opcode/cycle basis.  New CPU families make changes to improve out-of-order execution, branch predictions, µop cache, etc.  Also Windows & Linux becoming more involved with ARM CPUs should make life for those concerned about server & mobile performance interesting.  I can see CPU info to be very handy for running games & Node. 

Not sure the best way on how to capture CPU info though.

edit1: Perfect test case: http://jsperf.com/lzw-vs-lzjb/2  compression algorithm comparisons
When I first opened the test, the results (I assume from the test's author) for Chrome19 was LZJB:189,983 & LZW:210,084.  His/Her IE9 results favored LZJB: 273,401 vs 229,193.   I ran on my 1st gen i7 laptop, & got for IE8 2,884 vs 6,259, favoring LZW.  Ok, maybe IE9 made huge JS engine changes?  But I kept getting drastically different results for my Chrom19: LZJB: 63,738 &  LZW: 61,651; about 1/3 less then the original test, but also faster for LZJB.

Thanks for your consideration.

**Comment by tomByrer** [comment]
A bit more insight perhaps; 2 browsers on the same machine both using different builds for FireFox:
- older release version, 64bit, optimized I guess for P4+ or Core+
- newish beta, I assume compiled for 32bit OS, Intel P2+
  Both gave very different results for 4 tests, ran 4 times each.  The other tests were about the same.

http://jsperf.com/int2single-char

http://jsperf.com/single-char2int

Also: http://jsperf.com/cloning-an-object/22

**Comment by jdalton** [comment]
Thanks for the detailed report. Though we detect the [platform](https://github.com/bestiejs/platform.js/blob/a3abe463ba7adf3bcf9bafa7cfad51f7a1982443/test/test.js#L842-862) and display it on the test table title, Browserscope has its own detection scripts. This request would fit better with their issue tracker [here](http://code.google.com/p/ua-parser/issues/list) and/or [here](http://code.google.com/p/browserscope/issues/list).

**Comment by tomByrer** [comment]
Welcome!
Posted request here: http://code.google.com/p/browserscope/issues/detail?id=335&thanks=335&ts=1340179193
