### ISSUE TITLE
Custom colours for tests

### ISSUE THREAD

**Issue by dotherightthing** [mathiasbynens/jsperf.com#86]
Hi Mathias,

Thanks for another great app. :-)

Would it be possible for test creators to choose custom colours for the individual tests? 

I know that I would find it really useful to be able to gauge results at a glance rather than having to decipher the graph key each time.

Cheers,
Dan

**Comment by jdalton** [comment]
I will expose a `colors` array on the `ui.browserscope` object for devs to modify.

**Comment by jdalton** [comment]
Fixed [here](https://github.com/bestiejs/benchmark.js/commit/68fb0ec3f3b5add257a44b58cfe99af9aaa194c7). See http://jsperf.com/slugs for example usage.

**Comment by dotherightthing** [comment]
Nice! Thanks very much :-)
