### ISSUE TITLE
code in the FAQ doesn't seem to work w.r.t. setup

### ISSUE THREAD

**Issue by simonsarris** [mathiasbynens/jsperf.com#87]
http://jsperf.com/faq#setup-teardown

Using `ui.benchmarks[0].setup` seems to generate an error when used in a test, for example:

http://jsperf.com/content-display-strategies

**Comment by mathiasbynens** [comment]
Why are you using it here? Unless I’m missing something, you could simply use the “setup” form field in this case. What are you trying to do?

Preparation code runs before the tests are defined, hence the error.

/cc @jdalton

**Comment by jdalton** [comment]
@simonsarris Ya, you are right. We should tweak the FAQ entry to wrap it in a `setTimeout(...)`.

**Comment by mathiasbynens** [comment]
Wouldn’t it be better to update the FAQ saying that the “setup” and “teardown” fields can now be used for this? The FAQ entry was written back when there was only a “setup” field, which simply got injected in the global scope.

**Comment by jdalton** [comment]
@mathiasbynens The snippet mentions "setup" and "teardown" fields.

> **Is it possible to execute code before and after each clocked test loop, outside of the timed code region?**
> 
> That’s what `Benchmark#setup` and `Benchmark#teardown` are for. You can use the Setup and Teardown fields to use the same function(s) for all tests. To target specific tests, you can use `ui.benchmarks[0].setup = function(){ … };` (and/or teardown) in the Preparation Code field, where `0` is the zero-indexed test ID.

could be

> **Is it possible to execute code before and after each clocked test loop, outside of the timed code region?**
> 
> That’s what `Benchmark#setup` and `Benchmark#teardown` are for. You can use the Setup and Teardown fields to use the same function(s) for all tests. To target specific tests, you can use `setTimeout(function() { ui.benchmarks[0].setup = function(){ … }; }, 1)` (and/or teardown) in the Preparation Code field, where `0` is the zero-indexed test ID.
