### ISSUE TITLE
PHP ini setting incorrect

### ISSUE THREAD

**Issue by tomgrohl** [mathiasbynens/jsperf.com#88]
Hi,

I've got a similar PHP directive setting in my projects, but one of them in jsPerf looks like it is wrong.

On line 23 of start.php: https://github.com/mathiasbynens/jsperf.com/blob/master/_inc/start.php#L23

Should it be?

```
ini_set('session.use_only_cookies', '1'); // Don’t use query string
```

not:

```
 ini_set('use_only_cookies', '1'); // Don’t use query string
```

This is not too big an issue as PHP defaults to true for this directive, but thought I'd mention it.

**Comment by mathiasbynens** [comment]
Fixed in b85661a7496b5ad12563b104711e38abbe7d4011, thanks!
