### ISSUE TITLE
Normalization of results by system performance

### ISSUE THREAD

**Issue by Dither** [mathiasbynens/jsperf.com#92]
Is it possible to add an option to normalize results from various systems by measuring some predefined simple operation performance on them in advance and dividing corresponding results by those values?

**Comment by jdalton** [comment]
I believe @broofa is doing experiments with just that, [jsscore](https://github.com/broofa/jsscore).

**Comment by jdalton** [comment]
Closing as stale. We'll still keep an eye on the popularity of the request.
