### ISSUE TITLE
Can't see any test page in IE9

### ISSUE THREAD

**Issue by hbstone** [mathiasbynens/jsperf.com#94]
In IE9 on Win7, I can't seem to get to any test page. I can see jsperf.com and start to browse the test cases, but any link I click to open a specific test case gets into a redirect loop and breaks IE with the error "We were unable to return you to jsperf.com."

Consistently reproducible for me for any test case I attempt to look at, either from /browse, finding a page via Google, or pasting a URL directly.

**Comment by jdalton** [comment]
Checkout [this FAQ entry](http://jsperf.com/faq#ie9-java) and see if it helps.
