### ISSUE TITLE
Feature suggestion : clone tests

### ISSUE THREAD

**Issue by Ayms** [mathiasbynens/jsperf.com#96]
When we want to run tests that are similar but that we want to separate, maybe it would be helpfull to have the possibility to clone the tests (example: http://jsperf.com/property-lookup-undefined-2 be a clone at construction of http://jsperf.com/property-lookup-undefined that is modified afterwards, so we don't have to rewrite or copy/paste everything)

**Comment by usmonster** [comment]
:+1:

**Comment by caitp** [comment]
I want this :( Can we do this?

**Comment by jdalton** [comment]
Closing as stale. We'll still keep an eye on the popularity of the request.

**Comment by usmonster** [comment]
I'm still for it, for what it's worth. Need help implementing this?

**Comment by mathiasbynens** [comment]
This repository won’t be updated anymore. jsPerf development has moved to https://github.com/jsperf/jsperf.com.
