### ISSUE TITLE
Firefox hangs during test

### ISSUE THREAD

**Issue by s1monm** [mathiasbynens/jsperf.com#98]
I am experiencing issues with Firefox 15.0.1 in gathering results for the following test.  http://jsperf.com/pubsub-vs-eventbinding/4

Firefox just hangs after a while either in the 2nd or 3rd test case.  I have tried setting the dom.max_script_run_time setting in FireFox to 50 to see if that would resolve the issue but it does not.  All other browsers that I have tested return results.  Firefox did return results when there was only one test case.

**Comment by jdalton** [comment]
Closing because of lack of interest. Lots of tests are bad or awkward but these are a bit to complex to dig into. Most likely an issue with the test and not jsPerf.
