### ISSUE TITLE
Suggestion: create groups of tests

### ISSUE THREAD

**Issue by rentalhost** [mathiasbynens/jsperf.com#99]
It can be a simple suggestion to implement. Just allow set a "group label" for each item. For instance:

```
jQuery speed test

Test #1: group prev; title: jQuery17.prev()
Test #2: group prev; title: jQuery18.prev()
Test #3: group prev; title: jQuery19.prev()

Test #4: group next; title: jQuery17.next()
Test #5: group next; title: jQuery18.next()
Test #6: group next; title: jQuery19.next()
```

I know that the correct is create two jsperf pages, but generally it doesn't happen. The page will seems like it:

![Example](http://imageshack.us/a/img607/6537/semttulokth.png)

**Comment by jdalton** [comment]
Closing as stale. We'll still keep an eye on the popularity of the request.

**Comment by atsepkov** [comment]
+1
